Cargo.toml
evm_arithmetization/Cargo.toml
mpt_trie/Cargo.toml
proof_gen/Cargo.toml
trace_decoder/Cargo.toml

Some were missed in #14, and in particular the plonky2 deps, my bad. Although only `plonky2` is used across multiple crates here, I've moved all `plonky2` related dependencies at the workspace level for easier version bumping.

Bring more dependencies to workspace level

---

trace_decoder/src/decoding.rs

There was actually already a PR for this, but it was to merge back into `john_temp_fix_branch`. That branch had another fix applied to it later on, so I figured that it's probably better to split them into two separate PRs.
This is identical to [18](https://github.com/0xPolygonZero/proof-protocol-decoder/pull/18) except that I addressed the requested changes in the comments, so hopefully this should be a easy review.

Withdrawls not in state trie fix

---

trace_decoder/src/processed_block_trace.rs

Although we were adding code that was created during a txn to the local code hash resolve table, it was not getting added to the "global" lookup table. Previously I was using this funny closure to resolve code hashes, but this is pretty
unusable as soon as you need to add new entries to the current table. I ended up replacing this with a struct called `CodeHashResolving`, which I think is a lot easier to read.

Code hash resolve fix + cleanup

---

evm_arithmetization/src/keccak/keccak_stark.rs
evm_arithmetization/src/keccak/round_flags.rs

Both the following constraints evaluate to the same constraint:
https://github.com/0xPolygonZero/zk_evm/blob/d0bc5ecef656eeb7fc0e335419c7b0e8f5b96282/evm_arithmetization/src/keccak/keccak_stark.rs#L278-L285
If $f = \text{local\\_values[reg\\_step(NUM\\_ROUNDS - 1)]}$ then
```rust
let filter = local_values[reg_step(NUM_ROUNDS - 1)]; 
yield_constr.constraint(filter * (filter - P::ONES)); 
```
corresponds to $f * (f - 1)$ and
```rust
let final_step = local_values[reg_step(NUM_ROUNDS - 1)]; 
let not_final_step = P::ONES - final_step; 
yield_constr.constraint(not_final_step * filter); 
```
corresponds to $(1-f)*f$

fix(evm_arithmetization): remove duplicate constraint in keccak_stark

---

mpt_trie/src/debug_tools/common.rs
mpt_trie/src/debug_tools/diff.rs
mpt_trie/src/debug_tools/query.rs
mpt_trie/src/lib.rs
mpt_trie/src/nibbles.rs
mpt_trie/src/special_query.rs
mpt_trie/src/trie_subsets.rs
mpt_trie/src/utils.rs

This PR adds the tooling needed to prune as aggressively as we were before while allowing us to detect the edge cases that were causing us to sometimes "over-prune".
Unfortunately I noticed as I was working on this PR that some public functions (`Nibbles::push_nibbles_back`) and other tests were missing that I needed. I decided to take care of that as well in this PR, so apologies for the additional noise.
The two new public functions that are needed upstream are:
- `path_for_query` (potentially rename?)
- `IntoTrieKey::into_key`
`path_for_query` returns minimal information (eg. key piece if available) on the nodes traversed by a query against a trie. `IntoTrieKey::into_key` is a trait that is used by `TriePath` & `TriePathIter` to extract the key of the query result. Note that the logic …

Additional tooling for allowing aggresive pruning logic

---

CHANGELOG.md
Cargo.toml
README.md
docs/usage_seq_diagrams.md
mpt_trie/src/lib.rs
proof_gen/README.md
trace_decoder/README.md

Includes:
- some basic README update
- CHANGELOG addition
- some typo fixes
- all plonky2 dependencies updated to refer to new crates.io versions 🥳

Prepare for release

---

CHANGELOG.md
mpt_trie/src/lib.rs
trace_decoder/src/lib.rs

Some changes required for the `eth-trie-tools` dependencies.

Update mpt_trie API

---

CHANGELOG.md
evm_arithmetization/src/cpu/kernel/asm/core/exception.asm
evm_arithmetization/src/cpu/kernel/asm/core/jumpdest_analysis.asm
evm_arithmetization/src/cpu/kernel/interpreter.rs
evm_arithmetization/src/cpu/kernel/tests/core/jumpdest_analysis.rs
evm_arithmetization/src/generation/prover_input.rs

This PR adds an extra verification to  `invalid_jump_jumpi_destination_common` that verifies that the jump destination is indeed not a jumpdest. This is done by non-deterministically guessing the closest previous opcode and verifying that  after calling `write_table_if_jumpdest`, the corresponding bit in `@SEGMENT_JUMPDEST_BITS` is still 0.
Closes #27.

Add non jumpdests

---

CHANGELOG.md
trace_decoder/src/decoding.rs

We were always using the final `ExtraBlockData` when padding a block. In the case of a single txn, when there are no withdrawals, we still prepend the txn with the dummy payload for efficiency, but this was leading to discrepancies when connecting the two.
This fixes it.

Fix trace decoder padding with dummy payloads

---

.github/CODEOWNERS

The messy duplication of Robin and me is because gh won't automatically add a global owner to a PR unless it's specified if there's a rule for that dir. Don't ask me why. I have no idea.

Add Will to code owners

---

trace_decoder/src/decoding.rs
trace_decoder/src/lib.rs
trace_decoder/src/processed_block_trace.rs
trace_decoder/src/trace_protocol.rs
trace_decoder/src/types.rs

This PR aims at documenting the trace-decoding folder by adding the 
```
#![deny(rustdoc::broken_intra_doc_links)]
#![deny(missing_debug_implementations)]
#![deny(missing_docs)]
```
flags.
closes #18

Document trace-decoder.

---

evm_arithmetization/src/cpu/kernel/parser.rs

Yet another commit to pacify clippy.
This one seems like a false positive, but it's kinda harmless so no big deal to disable it for the file where the lint is triggered.

Pacify clippy

---

CHANGELOG.md
evm_arithmetization/src/prover.rs
evm_arithmetization/src/verifier.rs

On `main` we can't run tests with a simple `cargo t --release` because of a quirk in the way doctests are compiled in Rust. Doctests do not "see" compilation attributes like e.g. `test`, `doctest` or, as is the case here, `debug_assertions` because they are treated as separate compilation units. 
To work around this, this PR moves the relevant `use` clauses to the one spot in the code where the `debug_utils` modules are actually used and removes the conditional compilation from the modules themselves. The same has to be done in `starky` and that must be merged and published before this PR can be merged. 
Depends on https://github.com/0xPolygonZero/plonky2/pull/1540 being merged and published.

Don't let doctest quirks stop testing in release mode

---

CHANGELOG.md
evm_arithmetization/src/cpu/kernel/tests/add11.rs
evm_arithmetization/src/prover.rs

We need stronger testing through both the runner, the test chain, and L1 blocks, to prevent regressions and to support debugging efficiently.
Since #56 has been merged, we can leverage it to support full CPU execution without generating the traces, effectively just going through the kernel, thus allowing faster and cheaper testing without lower memory requirements.
This PR introduces such method for testing purposes.

Add utility method for testing CPU execution

---

CHANGELOG.md
Cargo.toml
evm_arithmetization/Cargo.toml
mpt_trie/Cargo.toml
proof_gen/Cargo.toml
trace_decoder/Cargo.toml

Also includes bumping `starky` to `v0.2.1` to fix `doctest` running in release mode: https://github.com/0xPolygonZero/plonky2/pull/1549
new releases to be published **AFTER** #73 is merged

Bump all crates to v0.1.1

---

CHANGELOG.md
evm_arithmetization/src/generation/state.rs

Follow-up from #56.
Upon `KernelPanic`, we print some info on where the error arised within the kernel, with the current stack and kernel memory.
With #56, we store memory elements as `Option<U256>` instead of `U256`, which makes the logs kind of heavy:
```bash
WARN [evm_arithmetization::witness::transition] Kernel panic at panic
WARN [evm_test_runner::plonky2_runner] witness generation failed with error: KernelPanic in kernel at
pc=panic, stack=[51], memory=[Some(42), Some(220), Some(37), Some(102), Some(80), Some(24), Some(170),
Some(31), Some(224), Some(230), Some(188), Some(102), Some(109), Some(172), Some(143), Some(194), Some(105), 
Some(127), Some(249), Some(186), Some(0), Some(0), Some(0), Some(0), Some(0), Some(0), Some(0), Some(0),
Some(0), Some(0), Some(0), Some(1), Some(0), …
```

Lighten up logging upon Kernel Panic

---

CHANGELOG.md
evm_arithmetization/src/cpu/kernel/asm/core/precompiles/blake2_f.asm

The `blake2` precompile is currently broken. This is because gas calculation is updating the number of rounds, effectively causing tests to blow up (kernel exit info storing the gas is scaled by $2^{192}$).
Because the stack is too large, I've moved the gas calculation prior to loading all the blake inputs.
The fix can be tested on the `blake2B` test variants with the test-runner. They now pass fine (before they would just hang forever). The variants of `CALLCODEBlake2f` and `CALLBlake2f` also pass fine, though variant case `d9g0v0_Shanghai` for both takes a long time.

Fix blake2 precompile

---

evm_arithmetization/src/arithmetic/addcy.rs
evm_arithmetization/src/arithmetic/arithmetic_stark.rs
evm_arithmetization/src/arithmetic/byte.rs
evm_arithmetization/src/arithmetic/divmod.rs
evm_arithmetization/src/arithmetic/modular.rs
evm_arithmetization/src/arithmetic/mul.rs
evm_arithmetization/src/arithmetic/shift.rs
evm_arithmetization/src/cpu/kernel/interpreter.rs
evm_arithmetization/src/cpu/kernel/tests/account_code.rs
evm_arithmetization/src/cpu/kernel/tests/add11.rs
evm_arithmetization/src/cpu/kernel/tests/core/access_lists.rs
evm_arithmetization/src/cpu/kernel/tests/core/jumpdest_analysis.rs
evm_arithmetization/src/generation/mod.rs
evm_arithmetization/src/generation/prover_input.rs
evm_arithmetization/src/generation/state.rs
evm_arithmetization/src/memory/segments.rs
evm_arithmetization/src/util.rs
evm_arithmetization/src/witness/operation.rs
evm_arithmetization/src/witness/traces.rs
evm_arithmetization/src/witness/transition.rs
evm_arithmetization/src/witness/util.rs

No concrete code change, just getting rid of a bunch of needless imports.
We still can't get rid of `allow(unused)` for now, there are too many warnings, but this is a first step.

Cleanup needless imports

---

CHANGELOG.md
evm_arithmetization/src/cpu/kernel/interpreter.rs
evm_arithmetization/src/generation/state.rs
evm_arithmetization/src/witness/transition.rs

Tiny other fix from #56.
Running CPU simulation outputs the correct total CPU cycles count at the end, but using `Debug` or `Trace` levels would display always `Cycle 0` with current `main` when going through the execution.
The issue was that we were still using `GenerationState` for `log_kernel_instruction` instead of the new `State` trait.
It also hides the final unpadded length print behind a `#[cfg(not(test))]` flag, as to not get the CI logs too verbose (it's getting spammed currently).

Fix Cycle count in logs for interpreter

---

mpt_trie/src/trie_subsets.rs

Very straightforward change.
`plonky2` seems to always expect that leaf nodes are never hashed out directly. By "directly" I mean if you have a leaf that is never read/written to but is the direct child of a parent that is also not hashed, then if we hash the leaf it may be traversed over and panic. It's not clear to me if this always happens, but I have observed a leaf that had no reads/writes (and was hashed out) be hit by plonky2.
Let me know if this shouldn't be the case in `plonky2`.

Creating sub-tries now never hashes leaves

---

CHANGELOG.md
evm_arithmetization/src/cpu/kernel/interpreter.rs
evm_arithmetization/src/generation/mod.rs
evm_arithmetization/src/generation/state.rs

Yet another tiny bug fix post #56.
CPU simulation displays default values in `Debug` mode, because we initialize the interpreter with empty inputs, before setting them during preinitialization.
```logtalk
DEBUG evm_arithmetization::generation::state: Input signed_txn: None    
DEBUG evm_arithmetization::generation::state: Input state_trie: HashedPartialTrie { node: Empty, hash: RwLock { data: None } }    
DEBUG evm_arithmetization::generation::state: Input transactions_trie: HashedPartialTrie { node: Empty, hash: RwLock { data: None } }    
DEBUG evm_arithmetization::generation::state: Input receipts_trie: HashedPartialTrie { node: Empty, hash: RwLock { data: None } }    
DEBUG evm_arithmetization::generation::state: Input storage_tries: []    
DEBUG …
```

Fix generation inputs logging pre-transaction execution

---

CHANGELOG.md
trace_decoder/src/decoding.rs

Fairly minor, but while debugging I realized that we should (as the comment specifies) pass an empty iterator instead of `once`.
This saves a few thousand cycles on dummy payloads (tested against John's test chain).

Reduce state trie size for dummy payloads

---

.github/labeler.yml
.github/workflows/labeler.yml

Basic layout of an automatic labeler. Could be extended in the future.
For now, it will automatically label the crates touched, or add `specs` if the docs are being updated.
Note that we don't have to create any label beforehand, if it doesn't exist, the labeler will create it on the first occurence.

Add automatic labeler for PRs

---

evm_arithmetization/src/prover.rs

Tiny overlook of #86.
We should still return the underlying result from running the interpreter. The previous PR logs tries on failure but always returns an `Ok(())`.

Fix simulation output result

---

evm_arithmetization/src/cpu/kernel/asm/memory/metadata.asm
evm_arithmetization/src/cpu/kernel/constants/global_metadata.rs
evm_arithmetization/src/cpu/kernel/constants/mod.rs
evm_arithmetization/src/cpu/kernel/interpreter.rs
evm_arithmetization/src/generation/mod.rs
evm_arithmetization/src/generation/prover_input.rs
evm_arithmetization/src/recursive_verifier.rs
evm_arithmetization/src/verifier.rs

As per [EIP-7516](https://eips.ethereum.org/EIPS/eip-7516), `blobbasefee` should be retrieved from the `excess_blob_gas` stored in the block header, but is not a header field on its own.
The details on how this is computed are in [EIP-4844](https://eips.ethereum.org/EIPS/eip-4844#helpers).
For simplicity with higher layers of the stack, it's probably better to remove it from the plonky2 header to keep it as consistent as possible with an actual chain header. It's still taken as a prover input though, as blob fee market mechanism isn't implemented.

Remove `blobbasefee` from block header

---

CHANGELOG.md
mpt_trie/src/debug_tools/query.rs
mpt_trie/src/nibbles.rs
mpt_trie/src/special_query.rs
mpt_trie/src/trie_subsets.rs
mpt_trie/src/utils.rs
trace_decoder/src/decoding.rs
trace_decoder/src/processed_block_trace.rs
trace_decoder/src/types.rs

This PR is the last piece to tie together all of the pruning optimizations/fixes that have been going on over the past month. I ended up having to cherry-pick from a testing branch, so apologies if this is a bit messy (eg. `Requested PR changes for #39` somehow never got merged and was on the tip of another in progress branch that I needed, but I'm just going to leave that here for now).
The critical bits in this PR are:
- Logic in the decoder to handle the branch collapse edge case properly.
- Fix in creating trie-subsets with when to hash out extension nodes.
- The order of calls in `into_txn_proof_gen_ir` has changed in order to use `delta_out` (just contains info on collapsed nodes) when creating partial tries. I'm going to admit upfront that this section got a lot more complex and …

Now prunes tries properly (and more aggressively!) without hack

---

CHANGELOG.md
trace_decoder/src/compact/compact_prestate_processing.rs
trace_decoder/src/compact/compact_to_partial_trie.rs
trace_decoder/src/types.rs

Fixes the issue with hitting a hash node on block `17735424`.
Essentially the issue was we were making the assumption that a trie's root would always uniquely identify it, which is not the case when you have two otherwise identical tries except different nodes are hashed/unhashed. The previous impl did not have access to the account key when parsing the embedded storage trie within the account trie and relied on creating a temporary map between `trie_hash` --> `trie`. This map would at the end of the decoding process be used to connect accounts with their storage tries.
However, with the above issue, this meant that sometimes (apparently extremely rarely) an account's storage trie would get swapped out with another "identical" trie that had different nodes hashed out. In the case of …

Fixed trie hash collision issue when constructing storage tries

---

README.md

Adds a high-level view of the dependency graph between proving backend libs (plonky2-*, starky) and the local crates.
Should also help clarify the release flow when bumping versions.

Add dependency graph in README

---

CHANGELOG.md
evm_arithmetization/src/cpu/kernel/interpreter.rs
evm_arithmetization/src/generation/state.rs

Small PR to add the `clock` to `GenerationStateCheckpoint`, so we can fix the interpreter rollback by setting the clock correctly.

Add clock to GenerationStateCheckpoint and fix interpreter rollback

---

evm_arithmetization/src/cpu/kernel/interpreter.rs
evm_arithmetization/src/prover.rs

Some elements of the inputs of `generation_state` weren't properly propagated from `generate_segment` to `generate_traces`. The issue was about `contract_code`, making e.g. `extCodeHashDeletedAccountCancun_d0g0v0_Shanghai` fail, but we propagate the whole `TrimmedGenerationInputs` struct to avoid future problems.

Add trimmed inputs to `ExtraSegmentData`

---

evm_arithmetization/src/generation/mod.rs
evm_arithmetization/src/memory/memory_stark.rs
evm_arithmetization/src/witness/traces.rs

The unpadded `Memory` length doesn't reflect the true length, since it doesn't include `MemBefore` or the filling ops.
We also now display the unpadded length of `MemBefore` and `MemAfter`.

Fix trace lengths

---

CHANGELOG.md
README.md
evm_arithmetization/src/cpu/kernel/interpreter.rs
evm_arithmetization/src/generation/state.rs

Merge clock fix

---

CHANGELOG.md
evm_arithmetization/Cargo.toml
mpt_trie/Cargo.toml
proof_gen/Cargo.toml
trace_decoder/Cargo.toml

Preparation to do a release for all sub-crates.
Initially I was thinking that we could get away with only bumping individual crates as changes are made to them, but since the crates refer to each other with `{ version = "..." path = "..." }`, I think this forces us to always bump all crate versions together.
Also, you might notice that two crates moved to `0.2.0` instead of `0.1.2`. The reason for this is I'm trying very hard to follow [SemVer](https://semver.org/). I'm using a cargo tool called [cargo-semver-checks)](https://crates.io/crates/cargo-semver-checks), and it's showing that I changed some public facing functions and therefore requires a `minor` version bump. This doesn't apply to the two other crates, so I instead just bumped their `patch` versions. Also this is a bit of an …

Bumped all sub-crates

---

evm_arithmetization/src/cpu/kernel/asm/core/access_lists.asm
evm_arithmetization/src/cpu/kernel/asm/mpt/storage/storage_read.asm
evm_arithmetization/src/cpu/kernel/asm/mpt/storage/storage_write.asm
evm_arithmetization/src/cpu/kernel/asm/transactions/common_decoding.asm
evm_arithmetization/src/cpu/kernel/tests/core/access_lists.rs

SLOAD currently charges gas after loading the storage slot, which can cause issue in witness generation in case of OOG.
Change that by charging gas before loading the storage. 
Also refactor `insert_accessed_storage_keys` to now return `cold_access, value_ptr`.

Charge gas before SLOAD and refactor `insert_accessed_storage_keys`

---

evm_arithmetization/src/cpu/kernel/tests/receipt.rs

Following address bundling `encode_receipt` takes the full address as its first argument -- and not just the offset anymore. This means that `test_receipt_encoding` was no longer testing what it was supposed to: the final loop to check RLP values was actually done on an empty vector (since the encoding was no longer stored in `RlpRaw`, as it should). This PR fixes this by setting the initial RLP address correctly.

Make test_receipt_encoding more meaningful.

---

evm_arithmetization/src/all_stark.rs
evm_arithmetization/src/cpu/columns/general.rs
evm_arithmetization/src/cpu/cpu_stark.rs
evm_arithmetization/src/cpu/kernel/asm/account_code.asm
evm_arithmetization/src/cpu/kernel/asm/memory/syscalls.asm
evm_arithmetization/src/cpu/kernel/tests/account_code.rs
evm_arithmetization/src/generation/mod.rs
evm_arithmetization/src/generation/state.rs
evm_arithmetization/src/memory/columns.rs
evm_arithmetization/src/memory/memory_stark.rs
evm_arithmetization/src/witness/operation.rs
evm_arithmetization/src/witness/traces.rs

Implements the pruning of stale contexts. A context is stale when it returns to its parent context; after it returns, it can never be accessed again and can be omitted from the memory of subsequent segments.
To detect when a context goes stale, we instrument `SET_CONTEXT`, and check if `new_ctx < old_ctx`. Since contexts are attributed in a strictly increasing order, this means that `new_ctx` is the parent context of `old_ctx`, and thus that `old_ctx` is stale.
This check is made in the `CPU` table. All the stale `old_ctx` values are then transmitted to the `Memory` table via a CTL.
In `Memory`, for each row, we check if `ADDR_CONTEXT` is contained in the `PRUNED_CONTEXTS` column via a lookup. If that's the case, it will be omitted from the CTL to `MemAfter`.
~~This PR contains #109 and …

Add context pruning

---

evm_arithmetization/src/generation/mpt.rs
evm_arithmetization/src/generation/state.rs

Running a CPU simulation with the type 2 fails because of the different default values in the state trie. The default SMT is a vector of 4 0s, messing up the preinitialized segments logic inside the interpreter.
Actual proving logic is unaffected, this only matters in the context of continuations or witness-only generation.

Skip trie loading when being passed default inputs

---

evm_arithmetization/src/cpu/kernel/asm/transactions/type_0.asm

Was erroneously removed in #130.

Add `%alloc_rlp_block` back in `type_0.asm`

---

evm_arithmetization/src/cpu/kernel/asm/main.asm
evm_arithmetization/src/cpu/kernel/asm/transactions/type_0.asm
evm_arithmetization/src/cpu/kernel/asm/transactions/type_1.asm
evm_arithmetization/src/cpu/kernel/asm/transactions/type_2.asm

The MPT design requires RLP encoding while hashing the trie, hence calling `%alloc_rlp_block` at least once, preserving the section reserved for the txn RLP.
The SMT design doesn't need to RLP encode, hence needs an additional shift when initializing the RLP pointer to make sure we don't overwrite the txn data. This can be observed for instance when looking at the trace for `erc20` and removing the dummy `%alloc_rlp_block`, the empty access_list becomes overwritten with 199 (should be 192 = 0xc0).
@wborgeaud that's also why we could remove it for type-0 txns, they're too small to be overwritten :)

Fix data overwrite in RLP segment

---

CHANGELOG.md
evm_arithmetization/src/cpu/kernel/tests/account_code.rs
evm_arithmetization/src/cpu/kernel/tests/balance.rs
evm_arithmetization/src/cpu/kernel/tests/mpt/delete.rs
evm_arithmetization/src/cpu/kernel/tests/mpt/insert.rs
evm_arithmetization/src/generation/mpt.rs
evm_arithmetization/src/generation/trie_extractor.rs
mpt_trie/Cargo.toml
mpt_trie/src/nibbles.rs
mpt_trie/src/testing_utils.rs
mpt_trie/src/utils.rs

Swap out the internal U512 inside Nibbles with [u64;5].
Issue: https://github.com/0xPolygonZero/zk_evm/issues/104

feat: swap out the internal U512 inside nibbles

---

CHANGELOG.md
evm_arithmetization/src/cpu/kernel/interpreter.rs
evm_arithmetization/src/generation/state.rs

The merge of interpreter / generation state introduced a notion of preinitialized segments, decoupled from the actual `MemoryState` segments, which was only used for the `TrieData` segment in context 0.
This PR removes this unnecessary distinction, similarly to how things are done on the actual prover side. It also renames the `get_with_init` method on memory content access with `get_or_default`, as the distinction is simply returning always a value compared to the regular getter.

Remove interpreter-specific preinialization logic from State trait

---

proof_gen/Cargo.toml
proof_gen/src/constants.rs
proof_gen/src/proof_gen.rs
proof_gen/src/proof_types.rs
proof_gen/src/prover_state.rs

To test the type2 impl while the `trace_decoder` is being reworked, we can try adapting `eth-tx-proof` but the cross-crate references are a bit messy as `trace_decoder` and `proof_gen` have not been yet adapted with the type2 impl of `evm_arithmetization`.
This tweaks `proof_gen` to take into account the type2 switch, in a way that should be usable by `eth-tx-proof` for testing while #93 is being worked on.

Update `proof_gen` (partially) to accomodate for type2 changes

---

evm_arithmetization/src/keccak_sponge/columns.rs
evm_arithmetization/src/keccak_sponge/keccak_sponge_stark.rs

- Replace `is_final_input_len` with `is_padding_byte`
- Added constraints for padding
Fixes #156

fix(keccak-sponge): properly constrain padding bytes

---

CHANGELOG.md
trace_decoder/src/utils.rs

The decoder is always printing the storage tries in the logs, which can be quite cumbersome and noisy especially when the lowest log level is selected.
This moves it from `println!` to `log::debug!`
cc @bgluth

Reduce verbosity in logs

---

CHANGELOG.md
Cargo.toml
evm_arithmetization/src/all_stark.rs
evm_arithmetization/src/arithmetic/arithmetic_stark.rs
evm_arithmetization/src/byte_packing/byte_packing_stark.rs
evm_arithmetization/src/cpu/cpu_stark.rs
evm_arithmetization/src/keccak/keccak_stark.rs
evm_arithmetization/src/keccak_sponge/keccak_sponge_stark.rs
evm_arithmetization/src/memory/memory_stark.rs

Bumps deps to `plonky2` v0.2.2 and `starky` v0.4.0.
Includes CTL filtering simplification and compilation fix with AVX-512 instructions enabled.

Bump with latest starky

---

CHANGELOG.md
trace_decoder/src/decoding.rs

Simplify withdrawals logic

---

trace_decoder/src/decoding.rs
trace_decoder/src/processed_block_trace.rs

#168 didn't include withdrawals accesses into the initial payload state trie, causing issues when processing the last transactions. Tested against John's block witnesses.
This fixes it by adding them while doing the initial preprocessing.  Also updates some related outdated comments.

Fix withdrawals accesses in state trie

---

CHANGELOG.md
trace_decoder/Cargo.toml

Bumped `trace_decoder` for new `zk_evm` release (`v0.3.1`).
There is only one PR in this release (#176), and I think we can get away in this case with only bumping `trace_decoder`.

Bumped `trace_decoder` version for new `zk_evm` release

---

evm_arithmetization/src/all_stark.rs
evm_arithmetization/src/cpu/kernel/interpreter.rs
evm_arithmetization/src/cpu/kernel/tests/add11.rs
evm_arithmetization/src/fixed_recursive_verifier.rs
evm_arithmetization/src/generation/mod.rs
evm_arithmetization/src/generation/mpt.rs
evm_arithmetization/src/generation/state.rs
evm_arithmetization/src/keccak_sponge/keccak_sponge_stark.rs
evm_arithmetization/src/memory/memory_stark.rs
evm_arithmetization/src/memory_continuation/memory_continuation_stark.rs
evm_arithmetization/src/proof.rs
evm_arithmetization/src/prover.rs
evm_arithmetization/src/recursive_verifier.rs
evm_arithmetization/src/witness/operation.rs
evm_arithmetization/src/witness/state.rs
evm_arithmetization/src/witness/traces.rs
evm_arithmetization/src/witness/transition.rs
evm_arithmetization/src/witness/util.rs

No code refactor or whatsoever, just removing all dead code from initial continuations work.
Also removing `interpreter` specific methods from the `State` trait which probably came back from an imperfect merge with `develop`.

continuations: initial cleanup pass

---

evm_arithmetization/src/cpu/kernel/asm/main.asm
evm_arithmetization/src/fixed_recursive_verifier.rs
evm_arithmetization/src/prover.rs
evm_arithmetization/src/verifier.rs

Add the whole kernel code to the first `MemBefore` trace of a transaction, so that it doesn't need to be hashed inside the kernel.
This removes around 10k rows of `Keccak`, at the cost of 60k rows in `MemBefore` and `Memory` (the extra rows in `Memory` will be mitigated in a future PR).
In addition, this solves a critical soundness problem, as the kernel code segment was completely prover-provided up to the hashing in `global main`, which was allowing completely arbitrary code execution in the kernel.

Put kernel code in first MemBefore

---

evm_arithmetization/src/fixed_recursive_verifier.rs

@LindaGuiga This is what I meant by relying on `AggregationChildTarget<D>` instead. The current structs are semantically the same, just the internal fields are named differently.

Unify `AggregationChildTarget` structs and reduce nb of args in method

---

evm_arithmetization/src/cpu/kernel/asm/beacon_roots.asm
evm_arithmetization/src/cpu/kernel/asm/global_exit_root.asm
evm_arithmetization/src/cpu/kernel/asm/main.asm
evm_arithmetization/src/cpu/kernel/asm/mpt/accounts.asm
evm_arithmetization/src/cpu/kernel/asm/mpt/read.asm
evm_arithmetization/src/cpu/kernel/constants/mod.rs
evm_arithmetization/src/cpu/kernel/interpreter.rs
evm_arithmetization/src/generation/mpt.rs

@4l0n50 I squashed all our commits from the debug branch, and also renamed explicitely the GER and Beacon roots variables to `state_key` instead of `address`.

Some fixes to Cancun

---

evm_arithmetization/src/generation/mod.rs
evm_arithmetization/src/prover.rs

The new logging approach on zero-bin side isn't compatible with txn segmentation as is, as all segments for a given txn would be logged as the same process.
This change would allow splitting the logs on a segment basis, the new "base" proofs with continuations.

Add segment indexing

---

evm_arithmetization/src/verifier.rs
evm_arithmetization/tests/add11_yml.rs
evm_arithmetization/tests/basic_smart_contract.rs
evm_arithmetization/tests/erc20.rs
evm_arithmetization/tests/erc721.rs
evm_arithmetization/tests/log_opcode.rs
evm_arithmetization/tests/self_balance_gas_cost.rs
evm_arithmetization/tests/selfdestruct.rs
evm_arithmetization/tests/simple_transfer.rs
evm_arithmetization/tests/withdrawals.rs

This PR introduces `verify_all_proofs` and updates integration tests with this method.

Introduce verify_all_proofs and update integration tests

---

evm_arithmetization/src/cpu/kernel/asm/core/call_gas.asm

This PR modified the call gas logic to charge for call value gas prior to invoking the call. I have tested this on a prior failing block and it has solved the issue. 
closes #194

Charge call value gas prior to call

---

evm_arithmetization/src/cpu/kernel/interpreter.rs
evm_arithmetization/src/prover.rs
evm_arithmetization/src/witness/state.rs

Calling `simulate_all_segments_interpreter` would always start from `index = 0` up to the targeted segment.
Additionally, this refactors a bit segment generation.

continuations: Remove redundant simulation

---

evm_arithmetization/Cargo.toml
evm_arithmetization/src/lib.rs

- `trace_decoder` now needs to link against two versions of `evm_arithmetization`.
- Because `#[global_allocator]` can only appear once per build, we need a way to prevent this from occurring twice.
- It also seems to be best practice to only use `#[global_allocator]` in binaries, so maybe this is something that we should look at removing from this library. However, for the time being, this will allow us to do two links against this crate.

Added a feature flag to disable `jemalloc`

---

evm_arithmetization/src/cpu/kernel/asm/transactions/type_3.asm

We were not increasing the RLP blob length with the blob versioned hashes, which were then being ignored when processing type 3 txn hashing.
cc @wborgeaud, while looking at this, I noticed something concerning. The txn hash was invalid, but the return value of ECRECOVER wasn't `U256::MAX` (i.e. failure signal), but instead an arbitrary (wrong) recovered sender address.

Insert blob versioned hashes in signature payload for hashing

---

evm_arithmetization/src/cpu/kernel/asm/core/precompiles/blake2_f.asm
evm_arithmetization/src/cpu/kernel/asm/core/precompiles/kzg_peval.asm

Initial stack when entering `precompile_kzg_peval` wasn't correct (and similarly the `blake2f` one wasn't properly updated as it isn't the last precompile anymore).

Fix-kzg-precompile-init

---

trace_decoder/src/utils.rs

Remove remaining `println!` call in `trace_decoder` in favor of `trace!` logging level (and also moves similar `debug!` logging for storage tries to `trace!`) so that they don't appear all the time in runs.
@BGluth I believe you had mentioned these were not so useful in the end. I haven't removed them also I am never using them, so if you believe they should just be plainly removed, I can update the PR.

Remove print call in `trace_decoder`

---

trace_decoder/src/decoding.rs
trace_decoder/src/processed_block_trace.rs

This PR adds EIP-4788 specification within the `trace-decoder` preprocessing to account for the beacon block root update in the first txn payload.
It also simplifies the padding logic with dummy payloads in case we have less than 2 txns in a block. This is simply handled by prepending `Default` `ProcessedTxnInfo` to the vector of inputs to be then converted into generation inputs. These have no state / storage accesses, hence trimming will be as extreme as the custom `fully_hashed_out` method previously used for padding payloads (except that in case of padding, the first dummy payload will contain the beacon root contract in its state and targeted storage slots).
Tested against `jerigon` on https://github.com/0xPolygonZero/zero-bin/tree/feat/cancun

Update decoder processing for cancun

---

evm_arithmetization/src/cpu/kernel/asm/core/create_contract_account.asm

As per EIP-6780:
> _A contract is considered created at the beginning of a create transaction or when a CREATE series operation begins execution (CREATE, CREATE2, and other operations that deploy contracts in the future). If a balance exists at the contract’s new address it is still considered to be a contract creation._
The current implementation was only tagging an address as newly created if it was non existent.
This fixes the remaining failing Cancun blocks.

cancun: Fix EIP-6780 implementation

---

evm_arithmetization/src/cpu/kernel/asm/hash/sha2/compression.asm
evm_arithmetization/src/cpu/kernel/asm/hash/sha2/message_schedule.asm
evm_arithmetization/src/cpu/kernel/asm/hash/sha2/ops.asm
evm_arithmetization/src/cpu/kernel/asm/hash/sha2/temp_words.asm
evm_arithmetization/src/cpu/kernel/asm/hash/sha2/write_length.asm

Applies the tricks initially specified in the SHA1 specs for the macros `sha2_choice` and `sha2_majority`, as well as reducing `u32` addition chain overhead for already reduced inputs.
Yields ~4.6% savings for SHA2 precompile.

Amortize sha2 compression loop

---

.github/workflows/audit.yml

See usage at [rustsec/audit-check/usage](https://github.com/rustsec/audit-check?tab=readme-ov-file#usage).

ci: add cargo audit job

---

evm_arithmetization/src/cpu/kernel/interpreter.rs

Encountering an error while running the CPU in `simulation` mode (i.e. through the interpreter) would display a reverted stack, which can be confusing. Additionally, the interpreter was re-implementing stack reconstruction in a bloated way while we could reuse the implementation from the underlying generation state (assuming the stack is less than 10 elements long in unit tests, which is currently always the case).
The only downside is that the `interpreter`'s implementation of the `State` trait method `get_stack` requires a double call to `stack.reverse()`, although this method is only used upon CPU erroring, so this isn't an issue.

fix: Revert interpreter stack display

---

evm_arithmetization/src/fixed_recursive_verifier.rs
evm_arithmetization/src/proof.rs
evm_arithmetization/tests/empty_txn_list.rs

Also cleans-up the way accessing was performed in the public inputs sequence to be less error-prone & more readable.
closes #82

feat(continuations): trim public values at block proof level

---

evm_arithmetization/README.md

Update README in `evm_arithmetization` to refer to Cancun HF instead of Shanghai.

doc(cancun): update README

---

evm_arithmetization/src/arithmetic/addcy.rs
evm_arithmetization/src/cpu/columns/general.rs
evm_arithmetization/src/cpu/kernel/constants/txn_fields.rs
evm_arithmetization/src/cpu/kernel/interpreter.rs
evm_arithmetization/src/cpu/kernel/mod.rs
evm_arithmetization/src/cpu/kernel/parser.rs
evm_arithmetization/src/cpu/kernel/tests/account_code.rs
evm_arithmetization/src/cpu/kernel/tests/add11.rs
evm_arithmetization/src/cpu/kernel/tests/balance.rs
evm_arithmetization/src/cpu/kernel/tests/blobhash.rs
evm_arithmetization/src/cpu/kernel/tests/bls381.rs
evm_arithmetization/src/cpu/kernel/tests/core/access_lists.rs
evm_arithmetization/src/cpu/kernel/tests/core/jumpdest_analysis.rs
evm_arithmetization/src/cpu/kernel/tests/mpt/insert.rs
evm_arithmetization/src/cpu/kernel/tests/transaction_parsing/parse_type_0_txn.rs
evm_arithmetization/src/cpu/kernel/tests/transient_storage.rs
evm_arithmetization/src/curve_pairings.rs
evm_arithmetization/src/generation/prover_input.rs
evm_arithmetization/src/generation/state.rs
evm_arithmetization/src/generation/trie_extractor.rs
evm_arithmetization/src/lib.rs
evm_arithmetization/src/memory/segments.rs
evm_arithmetization/src/testing_utils.rs
evm_arithmetization/src/util.rs
evm_arithmetization/src/verifier.rs

Removes `#![allow(dead_code)]` from `evm_arithmetization`, and perform associated cleanup.
It's targeting `feat/cancun` as some modules weren't used for Shanghai.

chore(cancun): Cleanup and bring back `dead_code` lint for `evm_arithmetization`

---

evm_arithmetization/src/arithmetic/addcy.rs
evm_arithmetization/src/cpu/decode.rs
evm_arithmetization/src/fixed_recursive_verifier.rs
evm_arithmetization/src/prover.rs

Triggered since 1.80.
No concrete changes, just documentation indentation tweaks.

fix: `clippy::doc_lazy_continuation`

---

evm_arithmetization/src/proof.rs
trace_decoder/src/decoding.rs

Small fixes for cancun:
- the decoder was only adding the beacon block roots contract to the state trie preimage for the first payload, which was causing a Kernel panic in case of empty blocks (the second dummy payload has txn_nb = 0 and would attempt to access it as well)
- the second dummy payload for an empty block would have a txn counter set to 1 instead of 0
- following `blobbasefee` removal from block metadata, the `from_public_inputs` method hadn't been updated accordingly.

fix(cancun): dummy payloads and public input retrieval

---

trace_decoder/src/decoding.rs

`calldata` for initial payload as per EIP-4780 is currently encoded directly from its `H256` value, which may mess the final storage trie root when the hash MSB is 0. Switching its type to a `U256` before RLP encoding (as actual storage slot type is) fixes this edge case.
Detected with [witness-0007.json](https://github.com/0xPolygonZero/zk_evm/files/15462155/witness-0007.json)

fix(cancun): encode calldata for EIP-4780 as `U256`

---

evm_arithmetization/src/cpu/kernel/asm/core/precompiles/kzg_peval.asm
evm_arithmetization/src/cpu/kernel/tests/bls381.rs
evm_arithmetization/src/generation/prover_input.rs

Fix KZG precompile failures. They were previously aborting proof generation with PI errors. Now they properly throw a fault exception.
Tested with txn 10 of [witness-0006.json](https://github.com/0xPolygonZero/zk_evm/files/15457445/witness-0006.json)

fix(cancun): handle KZG precompile errors properly

---

evm_arithmetization/src/cpu/kernel/asm/memory/memcpy.asm
evm_arithmetization/src/cpu/kernel/asm/memory/syscalls.asm
evm_arithmetization/src/cpu/kernel/tests/mcopy.rs
evm_arithmetization/src/cpu/kernel/tests/mod.rs

cf comment in https://github.com/0xPolygonZero/zk_evm/pull/252#discussion_r1616433358: this handles properly cases of overlapping with risk of overwrite.
Also adds some tests from the [EIP](https://eips.ethereum.org/EIPS/eip-5656)

fix(cancun): revamp `MCOPY` with overlapping

---

evm_arithmetization/src/cpu/kernel/asm/memory/memcpy.asm
evm_arithmetization/src/cpu/kernel/asm/memory/metadata.asm
evm_arithmetization/src/cpu/kernel/asm/memory/syscalls.asm
evm_arithmetization/src/cpu/kernel/tests/mcopy.rs
evm_arithmetization/src/cpu/kernel/tests/mod.rs

Noticed while working with John's edge case txns.
We aren't checking for valid memory offsets, which would then cause the prover to panic and abort when performing the mem_cpy.
@wborgeaud I noticed we aren't performing this check for the other syscalls of the `wcopy` family. Don't you think we should?
Makes 4th txn of [witness-0233.json](https://github.com/0xPolygonZero/zk_evm/files/15458369/witness-0233.json) pass.

fix(cancun): `mcopy` check offsets

---

evm_arithmetization/src/cpu/kernel/asm/core/access_lists.asm
evm_arithmetization/src/cpu/kernel/asm/core/create_receipt.asm
evm_arithmetization/src/cpu/kernel/asm/core/process_txn.asm
evm_arithmetization/src/cpu/kernel/asm/main.asm
evm_arithmetization/src/cpu/kernel/asm/rlp/increment_bounded_rlp.asm
evm_arithmetization/src/cpu/kernel/interpreter.rs
evm_arithmetization/src/cpu/kernel/tests/add11.rs
evm_arithmetization/src/cpu/kernel/tests/init_exc_stop.rs
evm_arithmetization/src/generation/mod.rs
evm_arithmetization/src/generation/prover_input.rs
evm_arithmetization/src/generation/rlp.rs
evm_arithmetization/src/generation/state.rs
evm_arithmetization/src/prover.rs
evm_arithmetization/tests/add11_yml.rs
evm_arithmetization/tests/basic_smart_contract.rs
evm_arithmetization/tests/empty_txn_list.rs
evm_arithmetization/tests/erc20.rs
evm_arithmetization/tests/erc721.rs
evm_arithmetization/tests/log_opcode.rs
evm_arithmetization/tests/self_balance_gas_cost.rs
evm_arithmetization/tests/selfdestruct.rs
evm_arithmetization/tests/simple_transfer.rs
evm_arithmetization/tests/withdrawals.rs
trace_decoder/src/decoding.rs
trace_decoder/src/processed_block_trace.rs

Supersedes #122 and includes `trace_decoder` related change for customizable batch size.

Bring back support for multi-txn batches

---

evm_arithmetization/src/cpu/kernel/asm/journal/transient_storage_change.asm
evm_arithmetization/src/cpu/kernel/asm/main.asm
evm_arithmetization/src/cpu/kernel/asm/memory/transient_storage.asm
evm_arithmetization/src/cpu/kernel/tests/transient_storage.rs

The condition `If pos'' > @GLOBAL_METADATA_TRANSIENT_STORAGE_LEN we need to update the length` was always satisfied, because we were comparing the scaled `pos` with the unscaled `len`.
This PR also changes the length to be stored to be always scaled to reduce overhead in the loop, as well as fixes some stack comments / adds some more.

fix(cancun): correct search loop in transient storage

---

mpt_trie/src/nibbles.rs
mpt_trie/src/trie_ops.rs

This change is already in upstream (`develop`), but now `trace_decoder` which relies on `feat/type2` needs this as well, so this is just a simple back-port.

Added `Clone` to a few error types in `mpt_trie`

---

evm_arithmetization/src/cpu/kernel/asm/memory/core.asm
evm_arithmetization/src/cpu/kernel/constants/mod.rs
evm_arithmetization/src/memory/segments.rs

`SEGMENT_KERNEL_GENERAL_2` is no longer used anywhere, hence can be removed, with its associated utility macros.

cleanup: remove outdated segment

---

evm_arithmetization/src/cpu/kernel/interpreter.rs
evm_arithmetization/src/generation/state.rs

We currently copy the entire memory state before pruning stale contexts, which is wasteful. This tweaks the copy process to proceed to scanning & pruning on the fly.

perf(continuations): Only copy non-stale contexts

---

mpt_trie/src/builder.rs
mpt_trie/src/lib.rs

This PR introduces a `PartialTrieBuilder` struct that allows for for construction of a `PartialTrie` from a collection of nodes.

Add partial trie builder

---

CHANGELOG.md
evm_arithmetization/Cargo.toml
mpt_trie/Cargo.toml
proof_gen/Cargo.toml
trace_decoder/Cargo.toml

Supersedes #269, without including `plonky2` related dependencies bump.

Release 0.4.0

---

evm_arithmetization/Cargo.toml
evm_arithmetization/benches/fibonacci_25m_gas.rs
evm_arithmetization/src/cpu/kernel/asm/mpt/read.asm
trace_decoder/Cargo.toml
trace_decoder/benches/block_processing.rs
trace_decoder/src/trace_protocol.rs

This PR adds a few benchmarks in order to track the impact of future changes / refactoring on some parts of the codebase. Namely:
- CPU execution, going through a Fibonacci loop until 25M gas are consumed
- block processing, decoding the witness for block https://etherscan.io/block/19240650.

perf: add benchmarks for different components

---

.github/CODEOWNERS
.github/labeler.yml

I'll be also migrating all issues from `zero-bin` shortly.

ci: add labeler flag for new `zero-bin` crate + update `CODEOWNERS`

---

zero_bin/tools/prove_rpc.sh

Previous version is probably a leftover from latest refactorings, yielding an empty filename `b.log` which isn't carrying much information on its own.

misc(zero-bin): fix logging filename for test script

---

zero_bin/leader/src/cli.rs
zero_bin/leader/src/client.rs
zero_bin/leader/src/main.rs
zero_bin/tools/prove_rpc.sh

This PR proposes that we refactor the leader CLI such that instead of having one command per rpc type, we have a single rpc command with an argument for the rpc type. This reduces redundancy and makes the cli more extensible as more rpc types are added (e.g. reth).

Refactor `zero_bin` leader cli

---

Cargo.toml

Something happened in the merge `zero_bin` PR (#279) where a local-renamed dep (something that is not on `crates.io`) got set just with a semver. Somehow `Cargo` is still able to build fine (not sure how...), but `rust-analyzer` (at least on my end) fails to make it past parsing the root `Cargo.toml`. This PR fixes this issue.

Removed non-existing public dep `__compat_primitive_types`

---

evm_arithmetization/src/cpu/kernel/asm/core/transfer.asm

When calling `add_eth`, regardless if the target account already exists in the trie or not, sending a 0 amount will end-up being a no-op.
As such, we can skip trie access and journaling entries and exit early in such cases.

perf(evm_arithmetization): Check for zero amount early in `add_eth`

---

zero_bin/rpc/src/lib.rs

Resolves https://github.com/0xPolygonZero/zk_evm/issues/282

fix: optimize previous hashes retrieval

---

Cargo.lock
Cargo.toml
smt_trie/Cargo.toml
smt_trie/README.md
smt_trie/src/bits.rs
smt_trie/src/code.rs
smt_trie/src/db.rs
smt_trie/src/keys.rs
smt_trie/src/lib.rs
smt_trie/src/smt.rs
smt_trie/src/smt_test.rs
smt_trie/src/utils.rs

Resolves #313.
I took the time to preserve all commits from `feat/type2` that changed the files in `zk_evm/smt_trie`, so we're not going to have any history loss either which is kind of cool.

Bring `smt_trie` into `develop`

---

evm_arithmetization/src/cpu/kernel/asm/core/terminate.asm

Fix a potential issue with selfdestruct, which may try accessing an address that doesn't exist if its creation has been skipped following an `%add_eth` call with amount 0 when refunding.
What we do now during a selfdestruct refund process is:
- after `%add_eth`, check the amount sent
- if it is zero, check for account existence
- if it exists, add a journal entry
- otherwise, skip
- if it is non-zero, add a journal entry
Noticed while debugging linked list refactoring of mpt_trie_data with @4l0n50 and @LindaGuiga.

fix: do not add selfdestruct journal entry for skipped accounts

---

evm_arithmetization/src/cpu/kernel/asm/core/transfer.asm

fix from #322 
We still need to flag `recipients` of `add_eth` as touched addresses, even though we skip an empty transfer for efficiency, otherwise we _may_ not search for them during final empty account deletion.

fix: add recipient to `touched_addresses` even when skipping empty transfer

---

evm_arithmetization/src/cpu/kernel/asm/memory/memset.asm

Fairly minor, initially aiming at targeting the wrong stack descriptions highlighted by auditors (i.e. `// stack: DST, final_count, retdest` after the `%mstore_unpacking` call that should have been `// stack: DST', DST, final_count, retdest`, but realized we could also just reduce the overhead when calling `memset` on the last chunk.

perf: reduce overhead in final iteration of `memset`

---

zero_bin/.cargo/config.toml
zero_bin/common/src/prover_state/persistence.rs
zero_bin/tools/prove_rpc.sh
zero_bin/tools/prove_stdio.sh

Resolves #306.
A few notes:
- If we are ever working within the project directory (eg. we haven't just copied the binary to some random directory), it should always look for `circuits` in `zk_evm/zero_bin/tools/`. If we're not in the project workspace, then it should just use the current working directory.
- The cleanest way to get the project directory when working with cargo seems to be setting an environment variable in `.cargo/config.toml`. Let me know if there's a better way.
- The scripts in `tools` now always output to `tools/proofs` no matter what the CWD is.

Make leader work no matter what the CWD is

---

Cargo.lock
Cargo.toml
compat/Cargo.toml
compat/src/lib.rs
zero_bin/rpc/Cargo.toml
zero_bin/rpc/src/lib.rs
zero_bin/rpc/src/native/state.rs
zero_bin/rpc/src/native/txn.rs

This PR proposes that we migrate the `Compat` trait to `trace_decoder::types`. The rationale behind this migration is such that if there are clients that alloy based which want to integrate with the trace protocol they should not have to import the `rpc` crate to get access to the `Compat` trait and associated conversions. A concrete example of this is the integration of `reth` which is `alloy` based.

migrate compat to trace_decoder crate

---

Cargo.lock
mpt_trie/src/builder.rs

This PR modifies the logic for inserting short node variants into the trie builder. The updated logic also parses branch nodes as in some instances (when a short node is less than 32 bytes) short nodes are embedded directly into the branch node.
closes: #344

Parse embedded short nodes

---

evm_arithmetization/src/logic.rs

Addresses #312 for the logic stark. A few questions:
- Is there anything special needed for PRs that touch constraints (e.g. a version bump somewhere)?
- Would it be beneficial to add some generate-evaluate tests similar to those in [`arithmetic::addcy`](https://github.com/0xPolygonZero/zk_evm/blob/439b8c227cb7fd837fdfa850dbe8ec13669eb78c/evm_arithmetization/src/arithmetic/addcy.rs#L299-L353)?

Add `LogicColumnsView` struct for `LogicStark`

---

zero_bin/leader/src/client.rs

This was logging "_final_" results before we were actually done with the payload.
Additionally, because `prove_rpc.sh` script was calling `grep` on the logging file and exiting (with success) upon finding this line (`All proof witnesses have been generated successfully.`), this was resulting in the issue mentioned in #351 of skipping fully `trace_decoder` processing + zkCPU simulation for `test_only` runs.
closes #351

fix: properly log final results when due

---

zero_bin/rpc/src/native/state.rs

Tested against blocks 20175000 through 201750010.
closes #350

fix: Add beacon roots touched slots into `state_access` with native tracer

---

evm_arithmetization/src/cpu/kernel/asm/curve/secp256k1/ecrecover.asm
evm_arithmetization/src/cpu/kernel/asm/transactions/common_decoding.asm
evm_arithmetization/src/cpu/kernel/constants/mod.rs
evm_arithmetization/src/cpu/kernel/tests/transaction_parsing/parse_type_0_txn.rs

Address the issue on missing signature check.
Now decoding of `s` will check that `s < N//2 + 1` as per EIP-2, i.e. `s < ceil(N/2)`.

fix(kernel): Check valid range for s and add test

---

.github/workflows/jerigon.yml
zero_bin/prover/src/lib.rs

Resolves https://github.com/0xPolygonZero/zk_evm/issues/354
Problem was that a lot of one-shot channels were created and not awaited, so some async engine resource got depleted (I am poetic today :)).

fix: failed to send proof

---

zero_bin/rpc/src/lib.rs

Oversight of #346: the witness fetching step for the previous hashes was missing the update on the most distant block hash from the current block (i.e. index 0 in the `b_hashes.prev_hashes` array).

fix: tweak fetching of previous block hashes

---

evm_arithmetization/src/cpu/columns/general.rs

Addresses #340.
I'm very open to suggestions if there is a way to make this less cumbersome.
It could be nice to add some [miri](https://github.com/rust-lang/miri) tests for this and other conversions, but I can't think of a clean way to run them in the CI. Miri doesn't support inline assembly, so we would need a way to avoid running any test that touches assembly in plonky2. Adding cfg attributes to every other test seems prohibitive. Maybe a naming scheme for miri tests and a `cargo test` filter would be good enough?

fix(evm_arithmetization): Adjust layout of `CpuGeneralColumnsView`

---

zero_bin/rpc/src/lib.rs

Something silly that we missed in #370, is that the iterator length isn't bounded by the fixed, constant size of the target array we're filling up. Instead, we iterate over the whole vector which, following latest fix, is 1 item too long for half the blocks (those with even offset), causing an underflow when indexing.

fix: limit iterator length when fetching block hashes

---

trace_decoder/src/decoding.rs
trace_decoder/src/utils.rs

Withdrawals amounts that are written in blocks are in `gwei` unit (cf [EIP-4895](https://eips.ethereum.org/EIPS/eip-4895#new-field-in-the-execution-payload-withdrawals)). We were currently processing them as `wei`, causing invalid balances on the targets and yielding invalid final state root. This hasn't been caught beforehand because:
- we've tested block contiguity only on John's test chains (which contained no withdrawals)
- benchmarks were targeting single blocks, hence we didn't need to connect the "_invalid_" final state root with the initial state root of the next block
- we don't check the `withdrawals_root` in the statement, hence no discrepancy noticed
We'd need to add some sanity checks to compare with the block header, but the response we keep post RPC requests does not …

fix: scale withdrawals amount to gwei

---

Cargo.toml
compat/Cargo.toml
evm_arithmetization/Cargo.toml
evm_arithmetization/src/cpu/columns/general.rs
evm_arithmetization/src/cpu/kernel/asm/core/create_receipt.asm
evm_arithmetization/src/cpu/kernel/asm/core/jumpdest_analysis.asm
evm_arithmetization/src/cpu/kernel/asm/curve/bn254/curve_arithmetic/msm.asm
evm_arithmetization/src/cpu/kernel/asm/mpt/insert/insert.asm
evm_arithmetization/src/witness/traces.rs
mpt_trie/Cargo.toml
mpt_trie/src/builder.rs
mpt_trie/src/nibbles.rs
smt_trie/src/bits.rs
trace_decoder/src/decoding.rs
zero_bin/common/src/prover_state/circuit.rs
zero_bin/common/src/prover_state/cli.rs
zero_bin/common/src/prover_state/mod.rs
zero_bin/ops/Cargo.toml
zero_bin/prover/Cargo.toml
zero_bin/rpc/src/native/txn.rs
zero_bin/rpc/src/provider.rs
zero_bin/rpc/src/retry.rs
zero_bin/verifier/Cargo.toml

Just a couple tweaks. Includes
- `clippy::missing_const_fn`
- `taplo fmt`
- some stack comments fixes in the Kernel assembly code

`cancun`: cleanup pre-release

---

evm_arithmetization/src/cpu/kernel/asm/account_code.asm
evm_arithmetization/src/cpu/kernel/asm/core/create.asm
evm_arithmetization/src/cpu/kernel/asm/core/process_txn.asm
evm_arithmetization/src/generation/prover_input.rs

It was previously implemented as `PROVER_INPUT`.
closes #381

feat(type2): Implement bytecode padding rule in the kernel

---

zero_bin/ops/src/lib.rs

When passing `--save-inputs-on-error` flag, we automatically write to disk the `GenerationInputs` that caused the proof generation to fail. The current extension is `.log` which is a bit confusing, especially as we serialize them into a pretty JSON string.

Serialize flaky inputs as 'json' files

---

zero_bin/tools/prove_rpc.sh

Just prints out a warning in `prove_rpc.sh` if the user has a file descriptor limit that is deemed too small when they are running in native mode. Does not attempt to change the limit (should we? We don't need root for this).
If the limit is too small, then there's a good chance that we'll get various IO errors related to this with `native` mode. (#354 )

Now warns if file descriptor limit is too small for native mode

---

Cargo.lock
zero_bin/leader/src/cli.rs
zero_bin/leader/src/client.rs
zero_bin/leader/src/http.rs
zero_bin/leader/src/main.rs
zero_bin/leader/src/stdio.rs
zero_bin/prover/Cargo.toml
zero_bin/prover/src/cli.rs
zero_bin/prover/src/lib.rs

Resolves https://github.com/0xPolygonZero/zk_evm/issues/426

feat: reorganize cli params

---

zero_bin/tools/prove_stdio.sh

`nproc` doesn't exist for MacOS. Just tweaking the script to not have to manually change this line every time.

Make `prove_stdio.sh` work on apple chips

---

evm_arithmetization/src/cpu/kernel/aggregator.rs
evm_arithmetization/src/cpu/kernel/assembler.rs
evm_arithmetization/src/cpu/kernel/ast.rs
evm_arithmetization/src/cpu/kernel/evm_asm.pest
evm_arithmetization/src/cpu/kernel/mod.rs
evm_arithmetization/src/cpu/kernel/parser.rs

closes #409 
I ended up using a more general approach to handle arbitrary chunks of code within conditional blocks (initial description in #409 was only mentioning skipping code between two global labels, not it handles arbitrary chunks).
Now anything between:
```asm
#[cfg(feature = feature_foo)]
{
....
}
```
will be ignored.

feat: add conditional feature support in the kernel assembly

---

evm_arithmetization/src/cpu/kernel/asm/main.asm

If the `to` field is empty, the previous value is read, which should be 0. This PR sets the field to 0 before processing each transaction, so the value read in such cases is indeed 0.

Reinitialize TO transaction field in `main`

---

evm_arithmetization/src/cpu/kernel/asm/memory/syscalls.asm

Addresses Issue I of the audit report.

Add overflow check in `codecopy` 

---

evm_arithmetization/src/cpu/kernel/asm/core/util.asm

Addresses Issue J of the audit report, even though as the audit mentions:
> _this Issue [is] unexploitable in practice._

Check for overflow in `context_id` increment

---

trace_decoder/src/type1.rs
trace_decoder/src/typed_mpt.rs

#413 
Snippets from `0xaatif/typed-backend2` that fix the bug.
The basic change is
```diff,rust
struct FooTrie {
-    typed: TypedMpt<Vec<u8>>,
+    untyped: HashedPartialTrie,
}
```
The following oracle passes
```bash
cargo build --release 
RUST_LOG=info ./target/release/leader \
--runtime in-memory \
--load-strategy on-demand rpc \
--rpc-type native \
--rpc-url "$RPC_URL" \
--block-interval 19807080..19807081 \
--backoff 1000 \
--max-retries 1000
```

fix: `StorageTrie`, `ReceiptTrie` and `TransactionTrie` shouldn't use `TypedMpt`

---

evm_arithmetization/src/cpu/kernel/asm/memory/metadata.asm
evm_arithmetization/src/cpu/kernel/asm/memory/syscalls.asm

Addresses Issue H of the audit report.

Ensure proper `offset + size` bounds in `wcopy`

---

evm_arithmetization/src/cpu/kernel/asm/core/exception.asm

The minimum stack length requirement was not properly set for `TLOAD` / `TSTORE` opcodes.

fix: set min stack length for transient opcodes

---

evm_arithmetization/Cargo.toml
evm_arithmetization/src/cpu/kernel/constants/mod.rs

closes #266 
If anyone has a suggestion for a better feature name, happy to change it.

Increase `MAXCODESIZE` for Polygon PoS

---

evm_arithmetization/src/generation/state.rs

`stack_peek` throws an exception if the stack is too small. But we also use `stack_peek` for debugging purposes, which might throw unwanted exceptions. This PR fixes this by ensuring the stack is not empty before carrying out the debugging operations.

 Fix jump_to

---

evm_arithmetization/src/witness/traces.rs

The computation of the displayed unpadded Arithmetic trace length was incorrect and gave a number too low.

Fix Arithmetic trace length

---

mpt_trie/src/builder.rs
mpt_trie/src/debug_tools/diff.rs
mpt_trie/src/debug_tools/query.rs
mpt_trie/src/debug_tools/stats.rs
mpt_trie/src/nibbles.rs
mpt_trie/src/special_query.rs
mpt_trie/src/trie_hashing.rs
mpt_trie/src/trie_ops.rs
mpt_trie/src/trie_subsets.rs
mpt_trie/src/utils.rs

- I think for public libraries it's generally a good idea to add as many derives as possible to public types since we want to make these types as easy to use as possible for the user.
- This PR just goes through and adds derives where possible (for all of the cases where we don't need to add any manual trait impls).

Added derives to `pub` types where possible for `mpt_trie`

---

evm_arithmetization/src/memory/columns.rs
evm_arithmetization/src/memory/memory_stark.rs

Changes the preinitialization constraints.
Now, the given segments (currently `Code`, `TrieData`, `AccountsLinkedList` and `StorageLinkedList`) are exempted from zero-initialization at any context, and not only at context 0 for the last three. This shouldn't be an issue since these three are never used by non-zero contexts.
This change adds a column, but allows to implement https://github.com/0xPolygonZero/zk_evm/issues/441 completely with a total of only 30 Memory columns. This change also allow for one extra preinitialized segment for free, if we need it.

Preinitialize segments in all contexts

---

evm_arithmetization/tests/two_to_one_block.rs

The test is being ignored and hence wasn't updated during the `Cancun` upgrade.
Also cleaning it up, as we were actually processing dummy payloads unlike what the initial code mentioned.

Fix 2-to-1 test for Cancun

---

evm_arithmetization/src/cpu/kernel/asm/main.asm
evm_arithmetization/src/cpu/kernel/tests/account_code.rs
evm_arithmetization/src/cpu/kernel/tests/mpt/insert.rs

This PR closes #406 .
This PR changes the order at which the tries are processed: the initial and final state tries are processed and hashed after the transaction and receipt tries.

Process state trie at the end

---

zero_bin/common/src/prover_state/persistence.rs
zero_bin/verifier/src/main.rs

bug(zero-bin): verifier binary not picking up pre-processed circuits

---

evm_arithmetization/src/byte_packing/byte_packing_stark.rs
evm_arithmetization/src/byte_packing/columns.rs

Continuation of the work in https://github.com/0xPolygonZero/zk_evm/issues/312

feat: Implement `Columns` view for `BytePackingStark`

---

zero_bin/tools/prove_stdio.sh

closes #361 
also redirects everything to logs instead of duplicating, to prevent clogging when debugging at the `Trace` level

chore: flush logs upon success

---

Cargo.lock
zero_bin/common/Cargo.toml
zero_bin/common/src/prover_state/mod.rs
zero_bin/common/src/prover_state/persistence.rs
zero_bin/leader/src/main.rs
zero_bin/verifier/src/main.rs
zero_bin/worker/src/main.rs

Resolves #375.
- Now attempts to use the OS's specific cache dir to store circuits.
- This is done by setting the env var `ZK_EVM_CACHE_DIR` if the user has not already set it, which allows the user to override the circuit cache directory if they want to.

Circuit cache dir now uses os cache dir

---

trace_decoder/src/lib.rs
trace_decoder/src/processed_block_trace.rs

The tracers only include the precompile addresses as hash nodes when a transaction reverted, which gets the decoder to fail building a minimal trie view because it is missing some account info (as these are flagged as `state_accesses`.
This is testable on block 444 of John's test chain (although the txn is a spam transaction, so I didn't include it in the test cases for CI runtime's sakes, as it takes ~89M CPU cycles).

fix: do not force precompile address access in case of txn reversion

---

trace_decoder/src/decoding.rs

We were picking the already incremented `txn_idx` in the error msg, which was causing discrepancies in error messages between _expected_ and _actual_ failing txn, cf #421 which caused unnecessary headache.

Fix txn indexing in error message

---

evm_arithmetization/src/cpu/kernel/asm/core/create_contract_account.asm

This was an erroneous fix, where the issue actually lied in the parsing of the Jerigon payload that didn't carry the actual account deletion information. More on this in #475.
The gist of it (from EIP-6780)
> A contract is considered created at the beginning of a create transaction or when a CREATE series operation begins execution (CREATE, CREATE2, and other operations that deploy contracts in the future). **_`If a balance exists at the contract’s new address it is still considered to be a contract creation`_**.

Revert "Fix `SELFDESTRUCT`"

---

evm_arithmetization/src/cpu/kernel/assembler.rs
evm_arithmetization/src/cpu/kernel/parser.rs

With the current implementation of conditional blocks, we cannot have conditional blocks including macros within a macro. This PR aims at allowing such a case scenario.

Allow features with macros within macros

---

evm_arithmetization/src/cpu/kernel/asm/main.asm
evm_arithmetization/src/generation/mpt.rs

Closes #473 .
This PR checks that the value stored in `GLOBAL_METADATA_TRIE_DARA_SIZE` after hashing the initial state trie is correct. Given that the initial trie is hashed and checked against the actual input hash, and that the final hash is constructed based on the initial trie, this should be enough to ensure soundness.
Note that when "guessing" the initial state trie, we do not store the storage values in the trie anymore: the value is added (and the pointer overwritten) anyway in `mpt_set_payload`.

Check the global variable `GLOBAL_METADATA_TRIE_DATA_SIZE`

---

evm_arithmetization/src/generation/mod.rs
evm_arithmetization/src/memory/columns.rs
evm_arithmetization/src/memory/memory_stark.rs
evm_arithmetization/src/memory/segments.rs
evm_arithmetization/src/witness/memory.rs

Addresses https://github.com/0xPolygonZero/zk_evm/issues/441.
Testing on some Ethereum blocks indicate an average gain in trace lengths of:
- 1.7% for Memory
- 9.2% for MemBefore
- 9.4% for MemAfter

Do not propagate zero values

---

.github/workflows/jerigon-native.yml
trace_decoder/src/lib.rs
zero_bin/common/src/prover_state/persistence.rs
zero_bin/rpc/src/native/txn.rs

handle case when contract creation was reverted

---

zero_bin/ops/src/lib.rs
zero_bin/prover/src/lib.rs

Closes https://github.com/0xPolygonZero/zk_evm/issues/390.

Parallelize test_only segment simulation

---

.cargo/config.toml
zero_bin/common/src/prover_state/persistence.rs
zero_bin/common/src/version.rs
zero_bin/leader/src/main.rs
zero_bin/rpc/src/main.rs
zero_bin/tools/prove_rpc.sh
zero_bin/tools/prove_stdio.sh
zero_bin/verifier/src/main.rs
zero_bin/worker/src/main.rs

Resolves #304.
Note however that the issue was actually something separate from what is mentioned in the issue. `zero-bin` was actually getting the version of `evm_arithmetization` from `Cargo.lock` and was not using tags. The issue was `zero-bin` was one directory deeper from `Cargo.lock` after it got migrated into `zk_evm`.

Fix: `zero-bin` is now able again to accesses `evm_arithmetization` for circuit versions

---

mpt_trie/src/partial_trie.rs
mpt_trie/src/trie_ops.rs
trace_decoder/src/lib.rs
trace_decoder/src/type1.rs
trace_decoder/src/typed_mpt.rs

Add a collapsing strategy for the edge case of a branch node with two children being collapsed into an extension node after the deletion of one the children.
cf #202 and #455 for reference
@0xaatif I don't consider the PR _ready_ yet, especially some more doc/clarification would be good but I'm opening it to get some feedback regarding the approach taken and if it matches how you were envisioning it following our chat.

Add collapse strategy to `PartialTrie` variants

---

trace_decoder/benches/block_processing.rs
trace_decoder/src/lib.rs
trace_decoder/src/processed_block_trace.rs
trace_decoder/tests/trace_decoder_tests.rs
zero_bin/prover/src/lib.rs

This is always `unimplemented!`
Closes #230

refactor: remove dead `client_code_hash_resolve_f`

---

Cargo.lock
evm_arithmetization/Cargo.toml
evm_arithmetization/src/fixed_recursive_verifier.rs
evm_arithmetization/src/lib.rs
evm_arithmetization/src/prover.rs
zero_bin/common/src/prover_state/mod.rs
zero_bin/ops/src/lib.rs
zero_bin/prover/src/lib.rs

Prevent failed CPU runs from panicking and aborting segment data generation, by returning a `Result` instead in the `SegmentDataIterator`.
Also allows to log inputs upon failure.
I had to tweak the `Result` type for `std` instead of `anyhow` in `evm_arithmetization` because of the need for `Deserialize`.

continuations: have segment iterator return a `Result`

---

zero_bin/leader/Cargo.toml
zero_bin/leader/src/client.rs
zero_bin/leader/src/http.rs
zero_bin/leader/src/main.rs
zero_bin/leader/src/stdio.rs
zero_bin/ops/Cargo.toml
zero_bin/ops/src/lib.rs
zero_bin/prover/Cargo.toml
zero_bin/prover/src/cli.rs
zero_bin/prover/src/lib.rs
zero_bin/tools/prove_rpc.sh
zero_bin/tools/prove_stdio.sh

Remove the `test_only` conditional compilation feature and make it part of the CLI arguments instead. Technically not related to continuations, but there are enough differences with `develop` that we might as well merge it here to avoid rebasing later.
Includes https://github.com/0xPolygonZero/zk_evm/issues/288.

Make test-only a CLI argument

---

Cargo.lock
zero_bin/leader/src/client.rs
zero_bin/leader/src/stdio.rs
zero_bin/prover/src/lib.rs
zero_bin/rpc/Cargo.toml
zero_bin/rpc/src/jerigon.rs
zero_bin/rpc/src/lib.rs
zero_bin/rpc/src/main.rs
zero_bin/rpc/src/native/mod.rs
zero_bin/rpc/src/native/state.rs

feat: retrieve prover input per block

---

trace_decoder/src/decoding.rs
trace_decoder/src/lib.rs
trace_decoder/src/processed_block_trace.rs

Clean up the contract and interface of `Hash2Code`.

refactor: Hash2Code

---

evm_arithmetization/src/cpu/kernel/asm/memory/syscalls.asm
evm_arithmetization/src/cpu/kernel/asm/mpt/linked_list/initial_tries.asm

`simple_transfer` integration test runs in 5.4sec on my machine now (45.6sec on the target branch).
also formats some `%stack` calls for readability

inline some macro calls

---

evm_arithmetization/src/fixed_recursive_verifier.rs
evm_arithmetization/src/generation/mod.rs
evm_arithmetization/src/generation/segments.rs
evm_arithmetization/src/generation/state.rs
evm_arithmetization/src/lib.rs
evm_arithmetization/src/prover.rs
proof_gen/src/proof_gen.rs
zero_bin/common/src/prover_state/mod.rs
zero_bin/prover/src/lib.rs

No concrete code change, just moving things around.
All the code regarding `GenerationSegmentData`, `SegmentDataIterator` etc.. should really not live in the prover module, but in a dedicated one within the `generation` main module instead

chore: Move segmentation related code into a dedicated submodule within `generation`

---

evm_arithmetization/src/cpu/kernel/asm/transactions/type_0.asm
evm_arithmetization/src/cpu/kernel/asm/transactions/type_1.asm
evm_arithmetization/src/cpu/kernel/asm/transactions/type_2.asm
evm_arithmetization/src/cpu/kernel/asm/transactions/type_3.asm

Addresses https://github.com/0xPolygonZero/zk_evm/issues/539.

Reuse txn rlp

---

Cargo.lock
zero_bin/rpc/Cargo.toml
zero_bin/rpc/src/lib.rs

Resolves https://github.com/0xPolygonZero/zk_evm/issues/510

feat: use eth_call with sc to retrieve block hashes

---

zero_bin/leader/src/client.rs
zero_bin/rpc/src/jerigon.rs
zero_bin/rpc/src/lib.rs
zero_bin/rpc/src/main.rs
zero_bin/rpc/src/native/mod.rs
zero_bin/rpc/src/native/state.rs
zero_bin/rpc/src/provider.rs
zero_bin/rpc/src/retry.rs

fix: limit number of connections

---

zero_bin/rpc/src/lib.rs

Now works with Jerigon, Alchemy, Quiknode

fix: eth_call for previous block hashes

---

evm_arithmetization/src/fixed_recursive_verifier.rs
evm_arithmetization/src/proof.rs
evm_arithmetization/src/recursive_verifier.rs
evm_arithmetization/tests/two_to_one_block.rs
proof_gen/src/proof_types.rs

Also rename some methods in `proof` module to clarify that they are declaring `public_inputs` as opposed to arbitrary targets, accordingly to the regular terminology used in `circuit_builder` methods on the plonky2 side.
closes #525

Prune non-necessary values from `PublicValues` prior 2-to-1 aggregation

---

trace_decoder/src/lib.rs

Simply halves the block in two chunks in case the initial batch size is too large, to prevent wasting ressources on dummy payloads.
closes #457 
Follow-up work mentioned #518 will improve on this but this requires additional benchmarkings / analysis of how much our instances can optimally handle.

`trace_decoder`: Tweak batch size for small blocks

---

evm_arithmetization/src/cpu/kernel/asm/mpt/linked_list/linked_list.asm
evm_arithmetization/src/cpu/kernel/asm/mpt/storage/storage_read.asm
evm_arithmetization/src/cpu/kernel/asm/transactions/common_decoding.asm

I initially just wanted to reduce the overhead around `storage_key_exists` as we now don't store storage value pointers but the values directly, but then I realized a bunch of stack descriptions in `linked_list.asm` were outdated, following #433

Reduce overhead in storage reads and fix stack descriptions

---

evm_arithmetization/src/curve_pairings.rs

The issue arising in some randomized samples of the pairing test was that the accumulated scalar was ending to be 0.
As we normalize the accumulated pairing computation by multiplying the running product by `pairing(-acc.P, Q)`, this was yielding invalid results for `bn254`, as the infinity point is _not_ a valid curve point and hence the pairing operation wasn't actually defined for `-acc.P`.
The issue only affected the updated test, the KERNEL implementation is sound as checking input validity, and is being tested expecially against these cases with `test_ecpairing_precompile_invalid_input`. 
closes #554

Fix pairing tests for null accumulated values

---

evm_arithmetization/src/cpu/kernel/evm_asm.pest
evm_arithmetization/src/cpu/kernel/parser.rs

Kernel parsing logic now supports:
- conditional blocks based on _any_ of the listed features, similarly to the _any_ Rust attribute syntax, i.e.:
```asm
#[cfg(any(feature = cdk_erigon,polygon_pos))]
{
// Do something if any of `cdk_erigon` or `polygon_pos` features are enabled
}
```
Note that the default listing of features will behave as an `any` block:
```asm
#[cfg(feature = cdk_erigon,polygon_pos)]
{
// Do something if any of `cdk_erigon` or `polygon_pos` features are enabled
}
```
- conditional blocks based on _all_ of the listed features, similarly to the _all_ Rust attribute syntax, i.e.:
```asm
#[cfg(all(feature = cdk_erigon,polygon_pos))]
{
// Do something if both `cdk_erigon` and `polygon_pos` features are enabled
}
```
- conditional blocks based on negated features, similarly …

Expand conditional blocks logic in Kernel parsing

---

zero_bin/common/src/prover_state/persistence.rs
zero_bin/leader/src/main.rs

This:
- makes sure to trim the directory path prefix (by considering only the actual filename) to search for matches
- run the clean command ahead of config and runtime creation, to not have to pass any additional arguments nor go through needless preprocessing if calling `clean` with an actual missing permutation of ranges.
Tested on macbook M2 pro and Ubuntu 22.04.

Fix `clean` leader's command

---

Cargo.lock
common/src/lib.rs
evm_arithmetization/Cargo.toml
evm_arithmetization/src/testing_utils.rs
evm_arithmetization/tests/selfdestruct.rs
evm_arithmetization/tests/simple_transfer.rs
trace_decoder/src/decoding.rs

closes #618 
Note that `zk_evm_common` is technically only necessary as dev-dependency for `evm_arithmetization`, but it will be brought in as regular dependency soon (cf #605) anyway.

Clarify `eth_to_gwei` helper name and move to `common` crate

---

zero_bin/common/src/fs.rs
zero_bin/rpc/src/main.rs

- the sanity check on the RPC `fetch` command prevents to fetch individual witnesses with same checkpoint (say witnesses for block 1 and 2, both targeting genesis as checkpoint, if the goal is to prove first b1 and pass it as `--previous-proof` argument of the second payload
- `--previous-proof` expected a `ProofWithPublicInputs` but we always serialize elements as `arrays`

Small fixes to `rpc` and `common` modules

---

evm_arithmetization/src/cpu/jumps.rs
evm_arithmetization/src/cpu/kernel/aggregator.rs
evm_arithmetization/src/cpu/kernel/asm/core/call.asm
evm_arithmetization/src/cpu/kernel/asm/core/exception.asm
evm_arithmetization/src/cpu/kernel/tests/core/jumpdest_analysis.rs
evm_arithmetization/src/cpu/kernel/tests/mod.rs
evm_arithmetization/src/witness/transition.rs

Following Hermez design. Removes about ~10% CPU cycles.

feat(type2): Skip jumpdest analysis

---

trace_decoder/src/core.rs

The latest refactoring was missing an edge case of transactions fundings precompile addresses (the only way for them to be `touched` instead of simply _accessed_), which would then need to be _masked_ (not sure of the terminology) for the prover to be able to access the related account down the trie.
I've also moved the masking up as it seemed slightly clearer to me, i.e. :
- state writes -> always mask (fixes block 15 of the test chain)
- state accesses (no writes) -> do not mask precompiles upon failed txn (fixes block 35 of the test chain, I had actually commented it on the refactoring PR, this may be related to the linked ticket)
but I could leave it where it was if preferred.

Fix address masking in `trace_decoder` processing

---

zero/src/bin/leader.rs
zero/src/prover.rs
zero/src/prover/cli.rs

make pool size configurable

---

evm_arithmetization/src/fixed_recursive_verifier.rs

This PR aims at addressing #634.
In `create_block_circuit`, it range-checks `diff = timestamp - parent_timestamp - 1` between `0` and `2ˆ32`, as a way to ensure `timestamp > parent_timestamp`.

Check block_timestamp always increases.

---

evm_arithmetization/src/cpu/kernel/interpreter.rs
evm_arithmetization/src/cpu/kernel/tests/account_code.rs
evm_arithmetization/src/cpu/kernel/tests/mpt/linked_list.rs
evm_arithmetization/src/generation/linked_list.rs
evm_arithmetization/src/generation/state.rs

The steps `insert_all_slots_in_memory` and `insert_all_accounts_in_memory` actually don't do anything, because we're inserting exactly the accounts and slots we've already added when processing the trie data.
cc @4l0n50

Remove unnecessary overhead in linked list preprocessing

---

evm_arithmetization/src/arithmetic/arithmetic_stark.rs
evm_arithmetization/src/byte_packing/byte_packing_stark.rs
evm_arithmetization/src/cpu/cpu_stark.rs
evm_arithmetization/src/fixed_recursive_verifier.rs
evm_arithmetization/src/keccak/keccak_stark.rs
evm_arithmetization/src/keccak_sponge/keccak_sponge_stark.rs
evm_arithmetization/src/logic.rs
evm_arithmetization/src/memory/memory_stark.rs
evm_arithmetization/src/memory_continuation/memory_continuation_stark.rs
evm_arithmetization/src/poseidon/poseidon_stark.rs
evm_arithmetization/src/prover.rs
evm_arithmetization/src/verifier.rs

This PR simplifies the initialization of the per-table recursive circuits and their proof generation and verification code by using macros. Extracted from #624

Refactor recursive circuit initialization and per table proving and verification with macros

---

Cargo.lock
evm_arithmetization/src/fixed_recursive_verifier.rs
evm_arithmetization/src/generation/mod.rs
evm_arithmetization/src/generation/segments.rs
evm_arithmetization/src/prover.rs
evm_arithmetization/src/public_types.rs
mpt_trie/src/debug_tools/diff.rs
trace_decoder/benches/block_processing.rs
trace_decoder/src/core.rs
trace_decoder/src/lib.rs
trace_decoder/src/observer.rs
trace_decoder/src/typed_mpt.rs
trace_decoder/tests/consistent-with-header.rs
trace_decoder/tests/simulate-execution.rs
zero/Cargo.toml
zero/src/bin/rpc.rs
zero/src/bin/trie_diff.rs
zero/src/debug_utils.rs
zero/src/lib.rs
zero/src/ops.rs
zero/src/prover.rs
zero/src/prover/cli.rs
zero/src/trie_diff/mod.rs

feat: trie diff tool

---

evm_arithmetization/src/cpu/kernel/asm/core/access_lists.asm
evm_arithmetization/src/cpu/kernel/asm/core/exception.asm
evm_arithmetization/src/cpu/kernel/asm/core/util.asm
evm_arithmetization/src/cpu/kernel/asm/curve/bn254/curve_arithmetic/curve_add.asm
evm_arithmetization/src/cpu/kernel/asm/curve/bn254/curve_arithmetic/pairing.asm
evm_arithmetization/src/cpu/kernel/asm/curve/bn254/curve_arithmetic/twisted_curve_checks.asm
evm_arithmetization/src/cpu/kernel/asm/curve/bn254/curve_arithmetic/twisted_curve_mul.asm
evm_arithmetization/src/cpu/kernel/asm/curve/bn254/field_arithmetic/util.asm
evm_arithmetization/src/cpu/kernel/asm/curve/common.asm
evm_arithmetization/src/cpu/kernel/asm/curve/secp256k1/curve_add.asm
evm_arithmetization/src/cpu/kernel/asm/curve/secp256k1/ecrecover.asm
evm_arithmetization/src/cpu/kernel/asm/curve/secp256k1/lift_x.asm
evm_arithmetization/src/cpu/kernel/asm/curve/wnaf.asm
evm_arithmetization/src/cpu/kernel/asm/mpt/read.asm
evm_arithmetization/src/cpu/kernel/asm/mpt/util.asm
evm_arithmetization/src/cpu/kernel/asm/util/basic_macros.asm
evm_arithmetization/src/generation/mod.rs
evm_arithmetization/tests/two_to_one_block.rs

Removes the 3 logic operations initially required by the segmentation mechanism (at the cost of ~3 extra~ 1 extra CPU cycle per segment), to allow for full removal of `LogicStark` table when possible, following @sai-deng's approach on the Keccak table.
Also did a pass on binary ops in the Kernel, as most of them could be expressed differently at no extra cost, to try make it even more likely to happen (`simple_transfer` goes from 1112 to 173 binary ops).

perf: Remove some binary ops & make KERNEL `init` section free of logic operations

---

.github/actions/rust/action.yml
.github/workflows/lint.yml

I was seeing this weird behaviour:
```
Run cargo binstall taplo-cli
INFO resolve: Resolving package: 'taplo-cli'
INFO resolve: taplo-cli v0.9.3 is already installed, use --force to override
INFO Done in [15]
Run taplo fmt --check
/home/runner/work/_temp/54a69868-69ab-442e-9fca-6020599020c1.sh: line 1: taplo: command not found
```
In https://github.com/0xPolygonZero/zk_evm/actions/runs/11123847101/job/30908151308#step:4:16 (an empty commit)
Not sure what's going on, but let's use someone else's github action instead

fix(ci): use install-action instead of cargo-binstall

---

scripts/prove_rpc.sh
scripts/prove_stdio.sh

We used to have `./script.sh | tee log.out` for convenience to retrieve the errors arising in CI jobs, but this was quite cumbersome locally for quick testing runs, hence reverting to `&> log.out`, which obfuscates everything.
As a simple middle ground, we can print the logs only upon failure, to easily retrieve the failures on the CI while not clogging our terminals when testing

misc: print script logs upon failure

---

evm_arithmetization/src/cpu/kernel/tests/transient_storage.rs
evm_arithmetization/src/witness/transition.rs

`log_kernel_instructions` is a no-op in `INFO` mode (which is almost always used), but ensures (when running in `DEBUG` / `TRACE` mode) that the PC doesn't overflow the KERNEL size.
As @0xaatif observed, this would cause the transient storage tests to fail (and only if run in `DEBUG` or lower AND not isolated (otherwise the actual KERNEL static wouldn't be initialized).
I've renamed the static variable in tests for clarity, and updated the check to retrieve the actual KERNEL code length from the memory instead. The overhead (if non-negligible), doesn't matter because we don't care so much about perfs with lower-level tracing anyway.
closes #664

Fix flaky test when `DEBUG` logging is enabled

---

trace_decoder/src/core.rs

We are not adding a default new trie mapped to a created address, which can cause errors in parsing if trying to write to storage of a newly created account.
Fixes a bunch of `missing storage trie for address FOO` on the test chain (I'm not including new payloads on the test cases folder because I am still trying to debug follow-up issues with some of these blocks on the prover side, but I can share payloads, the `consistent-with-header` integration test passes now).

Fix decoder parsing with new storage tries

---

evm_arithmetization/src/cpu/kernel/asm/transactions/type_3.asm

Similarly to base gas used, this should be a hard failure if we can't pay the base blob fee. Also the previous macro used was invalid (wrong stack)

Fix invalid `blob_gas_fee` burn

---

zero/src/rpc/jumpdest.rs

#427 
@einar-polygon this is the more natural way to do what you're trying to do.
- using `serde(remote = ..)`
- not reserializing
- no needless async
Can you test that it works for your use case?

discuss: deser in #427

---

trace_decoder/src/core.rs

We're currently erroring when missing an entry in the `Hash2Code` map. The access being done upon `state_read` in a state write, I'm wondering whether we should _always_ expect the client to provide necessary information, or if we should _allow_ missing entries.
In the current state of things, block 1034, txn 0 (`0xcfaf63b718a548069b856e8ff6b27ad69c3e8ca84ae2ab6ae67c545ecf0b642c`) is failing to parse at the decoder stage because we're missing contract bytecode associated to this txn trace:
```json
"0xd18e94fa1353e8b3b72e64ffc4a64d28a98cdee1": {
"code_usage": {
"read": "0x4ab15219b84093c7fd1c51566743820f9383a50b34c3f302b5331f26a89ddc73"
}
},
```
However, the prover does not need it and processes the txn payload fine with the change on this branch. I think Jerigon here knows we can `skip` …

fix: missing code read in state write

---

evm_arithmetization/src/generation/mod.rs
mpt_trie/src/debug_tools/diff.rs
zero/src/bin/trie_diff.rs
zero/src/trie_diff/mod.rs

Resolves https://github.com/0xPolygonZero/zk_evm/issues/636

feat: trie multi diff comparison

---

evm_arithmetization/src/cpu/kernel/asm/core/jumpdest_analysis.asm
scripts/prove_stdio.sh

Replaces the current `write_table_if_jumpdest` ASM code with a simpler argument.
Reduces the kernel code by ~350 bytes (though a bit less because of the overlap with https://github.com/0xPolygonZero/zk_evm/pull/684) and removes ~2800 cycles for ERC721.

perf: Improve PUSH checking in JDA

---

zero/src/bin/leader/cli.rs
zero/src/bin/rpc.rs
zero/src/rpc/jerigon.rs
zero/src/rpc/jumpdest.rs
zero/src/rpc/mod.rs
zero/src/rpc/native/txn.rs

Resolves https://github.com/0xPolygonZero/zk_evm/issues/675

feat: block structlog retrieval

---

evm_arithmetization/src/cpu/kernel/asm/core/call.asm
evm_arithmetization/src/cpu/kernel/asm/core/process_txn.asm

Contract creations mark a checkpoint prior deployment, but regular contract calls do not, which can cause discrepancies in final state tries upon reversion if the recipient does not have enough funds to send back the initial txn amount to the sender. This unfortunately wasn't caught with the original Eth test suite because `TO` targets were always funded enough at the start.
This added checkpoint now makes sure every transfers are being reverted, before sending the initial value back to the initial.
@praetoriansentry 3.5/5

Fix contract call reversion 

---

evm_arithmetization/src/memory/segments.rs
evm_arithmetization/src/witness/memory.rs
evm_arithmetization/src/witness/traces.rs
evm_arithmetization/src/witness/util.rs

Benchmarking CPU frequency against the Fibonacci benchmark yields an average improvement of 16% in witness generation (1.08MHz -> 1.25MHz).

perf: Inline some hot spots in witness generation

---

evm_arithmetization/src/cpu/kernel/asm/main.asm
evm_arithmetization/src/cpu/kernel/constants/global_metadata.rs

Also deletes an unused global metadata
6.5/N @praetoriansentry

fix: reset global metadata fields in memory post txn processing

---

evm_arithmetization/src/cpu/kernel/asm/core/process_txn.asm

In some transactions, the kernel might process a transaction with contract creation and empty code. In `process_contract_creation_txn_after_constructor`, there is a check that the first byte is not `0xef`. The check works for empty contracts in the non-batched case since `SEGMENT_RETURNDATA` is empty in that case. However, in the batched case, the first byte might come from a previous transaction, if the current contract is empty. 
This PR addresses this issue by only checking the first byte when `code_size > 0`.

Fix check against 0xEF byte in contract creation.

---

Cargo.lock
Cargo.toml
evm_arithmetization/src/all_stark.rs
evm_arithmetization/src/fixed_recursive_verifier.rs
evm_arithmetization/src/recursive_verifier.rs
evm_arithmetization/src/verifier.rs
evm_arithmetization/src/witness/errors.rs
evm_arithmetization/tests/empty_tables.rs
evm_arithmetization/tests/two_to_one_block.rs

We are currently having serialization issues due to the addition of `DummyProofGenerator` on the `RootCircuitData`, which is causing the prover_state to not be deserializable properly, ruining caching mechanism with persistence mode activated.
This is currently pinned to `07c20447bfcdada6bd479bd8a13af26082923520` on the plonky2 side (i.e. related branch fix), and updates the codebase with all changes related to plonky2 bump, in addition to fixing the range in `two_to_one` test and adding a serialization check consistency on the `empty_tables` test.
sibling PR: https://github.com/0xPolygonZero/plonky2/pull/1634

Bump plonky2 (serialization fix)

---

evm_arithmetization/src/generation/state.rs

Address the ‘attempt to subtract with overflow’ issue that occurs when `max_cpu_len_log` is set to a small value (less than 7).
This PR will also help with the empty segment test, where we aim to use the minimal number of CPU cycles in the segment.

Fix max_cpu_len_log

---

evm_arithmetization/src/generation/mod.rs
evm_arithmetization/src/witness/traces.rs

fix: unused MemAfter table

---

evm_arithmetization/src/cpu/kernel/interpreter.rs
evm_arithmetization/src/generation/segments.rs
evm_arithmetization/src/testing_utils.rs

Thanks to @Nashtare for highlighting this issue. This PR moves the opcode_count functionality under the #[cfg(test)] attribute to prevent unnecessary overhead during witness generation in non-test environments.

Move opcode_count Under Test Configuration

---

Cargo.lock
trace_decoder/Cargo.toml
trace_decoder/src/core.rs
trace_decoder/src/lib.rs
trace_decoder/src/observer.rs
trace_decoder/src/tries.rs
trace_decoder/src/type1.rs
trace_decoder/src/type2.rs
trace_decoder/src/world.rs
zero/src/bin/trie_diff.rs

Closes #707
Follows #693 
Obsoletes #722 
- `Type2World` is ready for testing.
- Remove `TypedMpt`, and just fold it into `StateMpt`.
- Remove the `conv_hash` module.

feat: trait World for `trace_decoder`

---

.github/workflows/ci.yml
.github/workflows/jerigon-native.yml
.github/workflows/jerigon-zero.yml
.github/workflows/pr_checking.yml

Resolves https://github.com/0xPolygonZero/zk_evm/issues/663
Removed workflows manual check for conditional execution of tasks.
Github has already included mechanisms to disable to Ci run. To skip it, it is enough to include skip ci in the commit message (more details [here](https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-workflow-runs/skipping-workflow-runs)).

chore: remove conditional ci execution

---

.github/actions/rust/action.yml
.github/labeler.yml
.github/workflows/audit.yml
.github/workflows/book.yml
.github/workflows/ci.yml
.github/workflows/docker_build.yml
.github/workflows/docker_build_push.yml
.github/workflows/jerigon-native.yml
.github/workflows/jerigon-zero.yml
.github/workflows/labeler.yml
.github/workflows/lint.yml
.github/workflows/pr_checking.yml
.github/workflows/yamllint.yml

Resolves https://github.com/0xPolygonZero/zk_evm/issues/743

feat: add yaml linter

---

Cargo.lock
zero/Cargo.toml
zero/src/bin/trie_diff.rs

Closes #721
Replaces existing regex usage with macro from [lazy_regex](https://docs.rs/lazy-regex/latest/lazy_regex/macro.regex_captures.html) crate.
Improves the code by replacing slice indexing with `&str` tuple of the captured values.
Also avoids the regex being compiled in every iteration of the relevant `for` loop.

Replace regex in trie diff main

---

.github/workflows/pr_checking.yml
.github/workflows/shellcheck.yml
scripts/prove_stdio.sh

Resolves https://github.com/0xPolygonZero/zk_evm/issues/744

feat: add ci shellcheck

---

evm_arithmetization/src/cpu/kernel/asm/core/call.asm
evm_arithmetization/src/cpu/kernel/asm/core/create.asm
evm_arithmetization/src/cpu/kernel/asm/core/gas.asm
evm_arithmetization/src/cpu/kernel/asm/core/util.asm
evm_arithmetization/src/cpu/kernel/asm/memory/syscalls.asm
evm_arithmetization/src/generation/mod.rs
evm_arithmetization/src/witness/traces.rs

In `sys_call`s and `create_common`, `create_context` is called (and some values are set) before actually entering the new context. But between `create_context` and `enter_new_ctx`, some exceptions might arise, and the new context is therefore not pruned when it should. This PR aims at fixing this issue. It also reverts #738, since the changes should no longer be necessary after this fix.
Block 1033 was failing (with a wire set twice) without #738, but passes fine with this PR's changes.

Prune child context in create and call faults

---

.github/workflows/benchmark.yml
scripts/benchmark_input.sh

Resolves https://github.com/0xPolygonZero/zk_evm/issues/651
Here we download `proving_benchmark_results.txt` artifact form previous succesfull run.
We run the proving job with `$BENCHMARK_WITNESS` file.
We append the resulting time to the simple textual result file and upload it to artifacts repo.
Job is executed every night at 4AM and manually.

feat: github proving benchmark

---

.github/workflows/yamllint.yml
scripts/docker-compose.yml
scripts/prove_stdio_docker_compose.sh
zero/README.md

feat: prove stdio using amqp docker compose setup

---

zero/src/rpc/jerigon.rs

`cdk_erigon` renamed `eth_getWitness` to `zkevm_getWitness` for jerigon mode.

Fix witness endpoint for cdk

---

Cargo.lock
Cargo.toml
evm_arithmetization/Cargo.toml
evm_arithmetization/src/lib.rs
evm_arithmetization/src/tries.rs
evm_arithmetization/src/world.rs
trace_decoder/Cargo.toml
trace_decoder/src/core.rs
trace_decoder/src/lib.rs
trace_decoder/src/observer.rs
trace_decoder/src/type1.rs
trace_decoder/src/type2.rs

No functionality change, just moving things around for type2 integration.
@LindaGuiga Note that I haven't moved all the modules into `evm_arithmetization` as you had done initially, not sure whether this was for simplicity or because I overlooked something.

Move `World` trait and related into `evm_arithmetization` crate

---

Cargo.lock
Cargo.toml
evm_arithmetization/Cargo.toml
evm_arithmetization/src/lib.rs
evm_arithmetization/src/tries.rs
evm_arithmetization/src/world.rs
smt_trie/src/code.rs
smt_trie/src/utils.rs
trace_decoder/Cargo.toml
trace_decoder/src/core.rs
trace_decoder/src/lib.rs
trace_decoder/src/observer.rs
trace_decoder/src/type1.rs
trace_decoder/src/type2.rs
trace_decoder/src/world.rs

@0xaatif I took a shot at #779 because it was starting to collide with what I was doing on the type2 branch, please let me know what you think.
Also we'd like to move `World` trait and related structs to `evm_arithmetization` instead of the `trace_decoder` for easy reuse across case disjunction on the prover side. Do you have any objection? If not I could even add it to this PR.

Fix bytecode hashing for Type2 SMT

---

zero/src/bin/leader/cli.rs
zero/src/bin/rpc.rs
zero/src/bin/trie_diff.rs
zero/src/prover/cli.rs

All leader program args now have a corresponding env variable that can also set it. This should make it easier to deploy in certain settings.
There's a bit of a minor DRY violation with repeating `ZERO_BIN_` for each of the env args, but I don't think there's too much that we can do to get around this even if we consider proc macros. Let me know if anyone has any suggestions, but yeah otherwise I think this is fine.
Finally also note that some of the args are defined in `paladin`, so another PR will be needed to be created there to also add in `env` support.
Issue: #760

feat: Add env support to all leader prog args

---

Cargo.lock
evm_arithmetization/src/witness/operation.rs
evm_arithmetization/src/world.rs
smt_trie/Cargo.toml
smt_trie/src/bits.rs
smt_trie/src/code.rs
smt_trie/src/keys.rs
smt_trie/src/smt.rs
smt_trie/src/smt_test.rs
smt_trie/src/utils.rs

* Replace `ethereum_types::{H256, U256}` etc in `smt_trie` crate with `alloy::primitives` equivalents
* Use alloy compat module in `trace_decoder` crate
Relates to #229 w.r.t smt_trie crate only

Replace `ethereum_types` with `alloy::primitives` in `smt_trie` crate

---

scripts/prove_stdio.sh
zero/src/ops.rs
zero/src/prover.rs

Resolves  https://github.com/0xPolygonZero/zk_evm/issues/627
Resolves https://github.com/0xPolygonZero/zk_evm/issues/399
Resolves  https://github.com/0xPolygonZero/zk_evm/issues/403
Segmentation and task dispatch logic has been changed to handle proving of the individual segments of one batch on different workers. Aggregation is performed after the segments of one batch are proven (not waiting of segments of all the batches to be completed). Segments are generated sequentially and consumed immediately.

feat: revamp zero prove function
