evm_arithmetization/src/keccak/round_flags.rs

See https://github.com/0xPolygonZero/zk_evm/pull/48#issuecomment-1952284284

fix(evm_arithmetization): constrain keccak round flags to bits

---

mpt_trie/src/debug_tools/diff.rs

Snuck in during suggested changes for a PR.

Fixed trie diffs using inverted logic

---

evm_arithmetization/src/cpu/kernel/stack/permutations.rs

Addresses the clippy issue showing up in Brendan's PRs

A small clippy fix

---

mpt_trie/src/trie_ops.rs

I added a test to `mpt_trie` a while back when I thought there was an issue with cloning tries. There wasn't an issue in the end, but I thought that I might as well add this test to our current list of tests.

Added a test for trie cloning

---

evm_arithmetization/src/recursive_verifier.rs

Add debug function for better logging in development
Issue: https://github.com/0xPolygonZero/zero-bin/issues/11

chore: add debug function for better logging in development

---

evm_arithmetization/src/cpu/kernel/assembler.rs

cf requirement from https://github.com/0xPolygonZero/zero-bin/pull/47

Add a getter for the KERNEL codehash

---

evm_arithmetization/src/cpu/kernel/tests/account_code.rs
evm_arithmetization/src/cpu/kernel/tests/add11.rs
evm_arithmetization/src/cpu/kernel/tests/balance.rs
evm_arithmetization/src/cpu/kernel/tests/receipt.rs
evm_arithmetization/tests/log_opcode.rs

Adapts the previously commented out tests to work with the SMT logic

Fix broken type2 tests

---

CHANGELOG.md
evm_arithmetization/src/cpu/kernel/assembler.rs
evm_arithmetization/src/cpu/kernel/interpreter.rs
evm_arithmetization/src/generation/prover_input.rs
mpt_trie/src/debug_tools/diff.rs
mpt_trie/src/debug_tools/query.rs
mpt_trie/src/debug_tools/stats.rs
mpt_trie/src/nibbles.rs
mpt_trie/src/trie_hashing.rs
mpt_trie/src/trie_subsets.rs
mpt_trie/src/utils.rs
proof_gen/src/proof_types.rs
proof_gen/src/prover_state.rs
trace_decoder/src/compact/compact_prestate_processing.rs
trace_decoder/src/processed_block_trace.rs

Just doing a run of `clippy` with `-D clippy::missing_const_for_fn`.

Make some more functions constant

---

evm_arithmetization/src/lib.rs
proof_gen/Cargo.toml
proof_gen/README.md
proof_gen/src/lib.rs
proof_gen/src/proof_gen.rs
proof_gen/src/proof_types.rs
trace_decoder/src/decoding.rs
trace_decoder/src/lib.rs
trace_decoder/src/processed_block_trace.rs
trace_decoder/src/types.rs

feat: decouple trace_decoder and proof_gen
Issue: https://github.com/0xPolygonZero/zk_evm/issues/155

feat: decouple trace_decoder and proof_gen

---

CHANGELOG.md

Moved `Unreleased` changes to `0.3.0`

---

evm_arithmetization/src/cpu/kernel/interpreter.rs
evm_arithmetization/src/generation/prover_input.rs
evm_arithmetization/src/generation/state.rs
evm_arithmetization/src/witness/operation.rs
evm_arithmetization/src/witness/transition.rs

In this PR, the interpreter only carries out logs outside of jumpdest analysis.

Silence jumpdest analysis logs

---

smt_trie/src/smt.rs
smt_trie/src/smt_test.rs

Old branch that I never merged

SMT hash node

---

trace_decoder/src/compact/compact_prestate_processing.rs
trace_decoder/src/processed_block_trace.rs

Related to this [change in Erigon](https://github.com/0xPolygonZero/erigon/commit/7962859185b67a25a122a2315d36efe162795420)

fix: add multiple witness version check

---

evm_arithmetization/src/cpu/kernel/asm/transactions/common_decoding.asm

EIP-4844 specifies in the validity logic of type-3 txns that:
- versioned hashes list must not be empty for blob transactions
- each versioned hash should have the MSB set to `KZG_VERSIONED_HASH`, i.e. 1.
Additionally, I came to realize that all our `invalid_txn_N` labels aren't really necessary (though I kept using them for the logic of this PR), as we are starting from the assumption that we want to prove valid blocks, i.e. blocks that would have been validated by any honest full node.
Whenever we hit one of the current exceptions triggering an `invalid_txn_N`, we jump right to `txn_after` PC, hence skipping any remaining txn logic execution, and then proceed to update the receipt trie (the txn trie being already updated after parsing of the txn RLP). But an invalid txn cannot be …

fix(cancun): Check `versioned_hashes` validity during type-3 txn processing

---

docs/arithmetization/tables/cpu.tex
docs/arithmetization/tables/memory.tex
evm_arithmetization/src/arithmetic/shift.rs
evm_arithmetization/src/cpu/jumps.rs
evm_arithmetization/src/cpu/kernel/asm/core/access_lists.asm
evm_arithmetization/src/cpu/kernel/asm/core/call.asm
evm_arithmetization/src/generation/prover_input.rs
evm_arithmetization/src/proof.rs
mpt_trie/src/partial_trie.rs
mpt_trie/src/utils.rs
trace_decoder/README.md
trace_decoder/src/decoding.rs
trace_decoder/src/trace_protocol.rs
zero_bin/tools/prove_rpc.sh
zero_bin/tools/prove_stdio.sh
zero_bin/verifier/src/main.rs

Quick polishing ahead of airdrop farmers.

doc: fix typos

---

zero_bin/tools/prove_rpc.sh

Resolves https://github.com/0xPolygonZero/zk_evm/issues/323

fix: interval

---

.github/pr_checking.yml

ci: add PR check job

---

README.md
zero_bin/README.md

doc: Update global README and add mention of `ulimit`

---

CHANGELOG.md
Cargo.lock
Cargo.toml
evm_arithmetization/Cargo.toml
mpt_trie/Cargo.toml
proof_gen/Cargo.toml
trace_decoder/Cargo.toml

Last Shanghai release, following discussion during the sync.
Includes:
- `CHANGELOG` update
- versions bump

Release v0.5.0

---

proc_macro/Cargo.toml

Update config file for `proc-macro` crate

---

evm_arithmetization/src/memory/columns.rs
evm_arithmetization/src/memory/memory_stark.rs

Continuation of the work in #312

feat: Implement `Columns` view for `MemoryStark`

---

.github/workflows/jerigon-native.yml
.github/workflows/jerigon-zero.yml

feat: test native tracer

---

.github/CODEOWNERS

Note the file is considered "wrong" because of Will's IT issues but I've left him as that will be resolved at some point.
Any concerns from anyone?

Update CODEOWNERS to add more folks

---

mpt_trie/src/debug_tools/query.rs
mpt_trie/src/trie_subsets.rs

Made sub-trie errors better

---

zero_bin/prover/src/lib.rs
zero_bin/tools/prove_rpc.sh

Resolves https://github.com/0xPolygonZero/zk_evm/issues/513

fix: output block proof to array format

---

evm_arithmetization/src/cpu/kernel/asm/curve/secp256k1/ecrecover.asm
evm_arithmetization/src/cpu/kernel/asm/transactions/type_3.asm
evm_arithmetization/src/cpu/kernel/tests/transaction_parsing/mod.rs
evm_arithmetization/src/cpu/kernel/tests/transaction_parsing/parse_type_0_txn.rs
evm_arithmetization/src/cpu/kernel/tests/transaction_parsing/parse_type_1_txn.rs
evm_arithmetization/src/cpu/kernel/tests/transaction_parsing/parse_type_2_txn.rs
evm_arithmetization/src/cpu/kernel/tests/transaction_parsing/parse_type_3_txn.rs

Addresses https://github.com/0xPolygonZero/zk_evm/issues/538.

Add txn parsing tests

---

evm_arithmetization/src/cpu/kernel/asm/core/access_lists.asm
evm_arithmetization/src/cpu/kernel/asm/transactions/common_decoding.asm
evm_arithmetization/src/cpu/kernel/asm/transactions/type_3.asm
evm_arithmetization/src/cpu/kernel/constants/global_metadata.rs

Some clean-up that I missed after https://github.com/0xPolygonZero/zk_evm/pull/547.

Remove unnecessary global metadata

---

Cargo.lock
Cargo.toml
trace_decoder/tests/trace_decoder_tests.rs
zero_bin/common/src/provider.rs
zero_bin/rpc/src/lib.rs
zero_bin/rpc/src/native/state.rs

move from alloy as a git dependency to a `crates.io` one

chore: update alloy

---

evm_arithmetization/src/fixed_recursive_verifier.rs
evm_arithmetization/src/generation/mod.rs
trace_decoder/src/decoding.rs
trace_decoder/src/lib.rs
trace_decoder/src/processed_block_trace.rs

addresses #555 and associated comment

chore: fix some variable names and comments

---

.github/CODEOWNERS

Adding @0xaatif and @atanmarko for CI changes.

chore: Add additional people as code owners for CI related changes

---

zero_bin/prover/src/lib.rs

Resolves https://github.com/0xPolygonZero/zk_evm/issues/585

optimize: limit number of blocks proving in parallel

---

zero/src/bin/leader/client.rs

We do not perform anything related to the aggregation / block layers in `test_only` mode, but the sanity check on the leader side still forces us to pass expectedly correct values for `checkpoint-block-number` and/or `previous-proof` which is cumbersome for testing only.

misc: Do not perform sanity check on `test_only` runs

---

.github/workflows/ci.yml
.github/workflows/jerigon-native.yml
.github/workflows/jerigon-zero.yml
rust-toolchain.toml

build: pin toolchain

---

.github/workflows/audit.yml
.github/workflows/book.yml
.github/workflows/ci.yml
.github/workflows/docker_build.yml
.github/workflows/docker_build_push.yml
.github/workflows/jerigon-native.yml
.github/workflows/jerigon-zero.yml
.github/workflows/labeler.yml
.github/workflows/lint.yml

Resolves https://github.com/0xPolygonZero/zk_evm/issues/628

fix: add timeouts to ci tests

---

trace_decoder/src/core.rs

Came upon these when debugging the heavy test suite. We're missing the txn info in some error messages during decoder processing which makes debugging a bit hard. Also expands the full hex `code_hash`, instead of displaying `no code for hash 0x4ab1…dc73`.

Expand error messages

---

.github/workflows/ci.yml

Thanks to @muursh for the fix. This has been verified with commits ecb9943 and 78fce60 in #690.

Fix zero_bin test

---

trace_decoder/src/type2.rs
trace_decoder/src/wire.rs

fix: more robust SMT parsing

---

.github/workflows/audit.yml
.github/workflows/book.yml
.github/workflows/ci.yml
.github/workflows/lint.yml

ci: update actions/checkout@v3 -> v4

---

zero/src/block_interval.rs

Resolves https://github.com/0xPolygonZero/zk_evm/issues/788

fix: follow from block interval

---

CHANGELOG.md
Cargo.lock
Cargo.toml
evm_arithmetization/Cargo.toml
evm_arithmetization/src/get_challenges.rs
evm_arithmetization/src/prover.rs
evm_arithmetization/src/recursive_verifier.rs
mpt_trie/Cargo.toml
smt_trie/Cargo.toml
trace_decoder/Cargo.toml

- Bump with latest plonky2 release and adapt code
- Update CHANGELOG
- Bump local versions for continuations release

v0.7.0 release
